import { create } from "zustand";

export const useLanguage = create((set) => ({
    lang: localStorage.getItem("lang") || "en",
    setLang: (lang) => {
        localStorage.setItem("lang", lang);
        set({ lang });
    },
}));

export const translations = {
    en: {
        menu_group_main: "Main Operations",
        menu_group_marketing: "Marketing & CRM",
        menu_group_inventory: "Inventory Management",
        menu_group_setup: "Establishment Setup",
        menu_group_admin: "Administration & Roles",
        menu_group_reports: "Business Intelligence",

        dashboard: "Dashboard",
        subscription: "My Subscription",
        inventory: "Inventory",
        purchases: "Purchases",
        suppliers: "Suppliers",
        stock: "Stock",
        stock_logs: "Stock Logs",
        stock_transfer: "Stock Transfer",
        pos: "POS / Sales",
        branches: "My Branches",
        tables: "Tables & QR",
        products: "Products",
        categories: "Categories",
        kds: "Kitchen (KDS)",
        order_history: "Order History",
        staff_roles: "Staff & Roles",
        users: "Users / Staff",
        roles: "Roles",
        permissions: "Role Permissions",
        plans: "Subscription Plans",
        reports: "Reports & Insights",
        sales_report: "Sales Report",
        expenses: "Expenses",
        best_sellers: "Best Sellers",
        settings: "Settings",
        business: "Business Ecosystem",
        service_blueprints: "Service Blueprints",
        system_modules: "System Modules",
        logout: "Logout",
        profile: "My Profile",
        executive_dashboard: "Executive Insights Dashboard",
        real_time_metrics: "Real-time performance metrics for your coffee business network",
        marketing_title: "Smart Marketing & CRM",
        marketing_subtitle: "Identify and re-engage with your most valuable customers.",
        inactive_vips: "Inactive VIPs (>30 days)",
        total_loyalty: "Total Loyalty Members",
        recovery_rate: "Recovery Rate",
        at_risk_customers: "At-Risk Customers",
        refresh_analysis: "Refresh Analysis",
        all_loyalty_members: "All Loyalty Members",
        win_back_campaign: "Win Back Campaign",
        suggested_offer: "Suggested Offer",
        send_promotion: "Send Promotion",
        win_back: "Win Back",
        days_inactive: "Days Inactive",
        apply_filters: "Apply Filters",
        search: "Search",
        recent_activity: "Recent Activity",
        view_all_orders: "View All Orders",
        no_data: "No data available",
        customer_overview: "Customer Overview",
        financial_summary: "Financial Summary",
        sales_performance: "Sales Performance",
        total: "Total",
        loyalty_subtitle: "Search and manage your VIP members easily",
        find_member: "Find a Member",
        enter_card_phone: "Enter membership card number or phone number below",
        search_placeholder: "Search by Card ID or Phone...",
        active_tiers: "Active Tiers",
        levels: "Levels",
        prepaid_wallet: "Prepaid Wallet",
        no_recent_searches: "No recent searches",
        please_enter_card_phone: "Please enter a card number or phone!",
        total_sales: "Total Sales",
        total_expenses: "Total Expenses",
        net_profit: "Net Profit",
        tier: "Tier",
        last_visit: "Last Visit",
        never: "Never",
        member: "Member",
        points: "Points",
        order_count: "Order Count",
        kds_subtitle: "Manage live orders and brewing speed.",
        active_orders: "Active Orders",
        no_active_orders: "No active orders. Time for a coffee break!",
        no_kds_history: "No history for today.",
        start_btn: "Start",
        ready_btn: "Ready",
        done_btn: "Done",
        avg_transaction: "Avg Transaction",
        waste_title: "Waste & Damage Tracking",
        waste_subtitle: "Monitor and record inventory loss to protect your profit margins.",
        record_waste: "Record Waste",
        total_items_wasted: "Total Items Wasted",
        record_new_waste: "Record New Waste / Damage",
        record_now: "Record Now",
        select_item_type: "Select Item Type",
        finished_product: "Finished Product",
        raw_material_ingredient: "Raw Material / Ingredient",
        expired: "Expired",
        damaged: "Damaged",
        wrong_recipe: "Wrong Recipe",
        profit_margin: "Profit Margin",
        forecast_title: "AI Ingredient Forecasting",
        forecast_subtitle: "Based on your sales from the last 7 days, here is what you need for next week.",
        export_purchase_list: "Export Purchase List",
        supply_demand_analysis: "Supply vs. Demand Analysis",
        forecast_confidence: "Forecast Confidence",
        avg_daily_usage: "Avg Daily Usage",
        next_7_days_expected: "Next 7 Days (Expected)",
        suggested_purchase: "Suggested Purchase",
        sufficient: "Sufficient",
        no_forecast_data: "No enough sales data yet to generate forecast.",
        expected_usage_7d: "Expected Usage (7d)",
        forecast_recommendation: "Recommendation: Consider purchasing items marked in Gold before Monday.",
        performance_trends: "Performance Trends",
        revenue: "Revenue",
        growth: "Growth",
        distribution: "Distribution",
        live: "Live",
        now: "just now",
        account_settings: "Account Settings",
        general_info: "General Information",
        full_name: "Full Name",
        email_address: "Email Address (Login ID)",
        security_settings: "Security Settings",
        new_password: "New Password",
        confirm_password: "Confirm Password",
        leave_blank: "Leave blank to keep current",
        save_changes: "Save Changes",
        active_account: "Active Account",
        branch: "Branch",
        business_label: "Business",
        order_no: "Order No",
        date: "Date",
        status: "Status",
        amount: "Amount",
        payment_method: "Payment",
        cashier: "Cashier",
        all: "All",
        pending: "Pending",
        paid: "Paid",
        cancelled: "Cancelled",
        view_details: "View Details",
        order_details: "Order Details",
        order_detail: "Order Detail",
        subtotal: "Subtotal",
        tax: "Tax",
        discount: "Discount",
        print: "Print",
        export: "Export",
        filter: "Filter",
        items: "items",
        no_orders: "No orders found",
        order_management: "Order Management",
        track_orders: "Track and manage your orders efficiently",
        avg_order_value: "Avg Order Value",
        this_month: "This Month",
        total_revenue: "Total Revenue",
        subscription_limits: "My Subscription & Limits",
        overview: "Overview",
        billing_history: "Billing History",
        current_trial: "Current Trial",
        current_package: "Current Package",
        package_30_day_trial: "30-DAY TRIAL",
        started: "Started",
        expires_on: "Expires On",
        no_expiry: "No Expiry",
        days_remaining: "days remaining",
        days_ago: "days ago",
        expired_label: "Expired",
        upgrade_plan: "Upgrade Plan",
        resource_utilization: "Resource Utilization",
        staff_seats: "Staff Seats",
        store_branches: "Store Branches",
        sku_capacity: "SKU Capacity (Products)",
        unlimited: "Unlimited",
        need_more_capacity: "Need more capacity? Upgrading takes less than 1 minute.",
        compare_plans: "Compare Plans",
        subscription_history: "Subscription History",
        history_desc: "All your past and current subscription periods.",
        refresh: "Refresh",
        price: "Price",
        duration: "Duration",
        not_available: "Not Available",
        current: "Current",
        maybe_later: "Maybe Later",
        next_confirm: "Next: Confirm Upgrade →",
        currently_active: "Currently Active",
        upgrade_picker_desc: "Select a plan that fits your growing business needs. Permissions and limits will be updated instantly.",
        upgrading_to: "Upgrading to",
        month: "month",
        relogin_required: "Re-login Required",
        relogin_desc: "Please logout and login again to activate your new permissions and features.",
        upgrade_success: "Upgrade Successful! 🎉",
        full_access_to: "You now have full access to",
        active_until: "Active Until",
        got_it: "Got it! 🚀",
        days: "days",
        one_time: "One-time",
        lifetime: "Lifetime",
        permanent_access: "Permanent Access",
        upgrade: "Upgrade",
        pro_label: "PRO",
        premium_label: "PREMIUM",
        main_branch: "Main Branch",
        admin_label: "Admin",
        staff_label: "Staff",
        subscription_details: "Subscription Details",
        estimated_servings_label: "Total Estimated Servings",
        real_time_price: "Current price including waste",
        low_stock_warning: "Some ingredients are running low! Please restock soon.",
        after_waste: "After",
        estimated_cost_per_cup: "Estimated Cost Per Cup",
        will_deduct: "Will deduct",
        from_stock: "from stock",
        waste_factor_desc: "Waste % — Extra qty used due to spill/loss.",
        effective_qty: "Effective Qty",
        size: "Size",
        low_stock: "Low Stock!",
        select_material: "Select Material...",
        gram: "Gram",
        cups: "Cups",
        cost_per_cup: "Cost Per Cup",
        hide_header: "Hide Header",
        show_header: "Show Header",
        product_list: "Product List",
        add_new_product: "Add New Product",
        edit_product: "Edit Product",
        search_product: "Search product...",
        product_name: "Product Name",
        category_name: "Category Name",
        quantity: "Quantity",
        barcode: "Barcode",
        description: "Description",
        image: "Image",
        action: "Action",
        confirm_delete_product: "Are you sure you want to delete this product?",
        product_deleted: "Product deleted successfully",
        product_saved: "Product saved successfully",
        remove_data: "Remove data",
        confirm_remove_product: "Are you sure you want to remove this product?",
        total_products: "Total Products",
        menu_inventory: "Menu Inventory",
        add_new: "Add New",
        brand: "Brand",
        edit_product_title: "☕ Edit Product",
        new_menu_item: "☕ New Menu Item",
        sizes: "Sizes",
        add_size: "Add Size",
        addons: "Add-ons",
        add_addon: "Add Add-on",
        customize_coffee: "Customize Your Coffee / Options",
        mood: "Mood / Type",
        hot: "Hot",
        iced: "Iced",
        frappe: "Frappe",
        sizes_override_msg: "* If specific sizes are set below, they will override the Base Price in POS.",
        base_price_label: "Base Price",
        save_item: "Save Item",
        update_item: "Update Item",
        purchase: "Purchase",
        received: "Completed / Received",
        request: "Purchase Request",
        invoice_no: "Invoice Number",
        supplier: "Supplier",
        raw_material: "Raw Material",
        recipe: "Recipe Management",
        ingredients: "Ingredients",
        add_ingredient: "Add Ingredient",
        invoices: "Invoices",
        shop_managment: "Shop Management",
        table: "Table",
        product: "Product",
        category: "Category",
        sale: "Sale",
        order: "Order",
        user: "User",
        permission: "Permission",
        total_purchase: "Total Purchase",
        total_paid: "Total Paid",
        outstanding_balance: "Outstanding Balance",
        total_orders: "Total Orders",
        purchase_history: "Purchase History",
        new_purchase: "New Purchase",
        ref_no: "Ref #",
        paid_amount: "Paid Amount",
        balance: "Balance",
        save: "Save",
        cancel: "Cancel",
        receive_date: "Receive Date",
        note: "Note",
        total_amount: "Total Amount",
        receiving_now: "Receiving Now",
        supplier_list: "Supplier List",
        name: "Name",
        code: "Code",
        tel: "Tel",
        email: "Email",
        address: "Address",
        website: "Website",
        created_at: "Created At",
        edit: "Edit",
        delete: "Delete",
        add_new_supplier: "Add New Supplier",
        edit_supplier: "Edit Supplier",
        confirm_delete_supplier: "Are you sure you want to delete this supplier?",
        supplier_deleted: "Supplier deleted successfully!",
        raw_material_list: "Raw Material List",
        material_name: "Material Name",
        stock_status: "Stock Status",
        last_cost: "Last Cost",
        active: "Active",
        inactive: "Inactive",
        add_new_material: "Add New Material",
        edit_material: "Edit Material",
        initial_stock: "Initial Stock",
        min_stock_alert: "Min Stock Alert",
        in_stock: "IN STOCK",
        low_stock: "LOW STOCK",
        out_of_stock: "OUT OF STOCK",
        total_products_menu: "Total Products Menu",
        low_stock_products: "Low Stock Products",
        low_stock_materials: "Low Stock Materials",
        stock_logs_adjustments: "Stock Logs & Adjustments",
        manual_adjustment: "Manual Adjustment",
        filter_by_item_type: "Filter by Item Type",
        filter_by_type: "Filter by Type",
        date_time: "DateTime",
        category: "Category",
        transaction: "Transaction",
        change: "Change",
        staff: "Staff",
        reason: "Reason",
        stock_correction: "Stock Correction",
        inventory_item_type: "Inventory Item Type",
        select_item: "Select Item",
        action_type: "Action Type",
        qty_change: "Qty Change",
        remark_reason: "Remark / Reason",
        adjustment: "Adjustment",
        waste: "Waste",
        receive: "Receive",
        unit: "Unit",
        quantity_in_stock: "Qty in Stock",
        branch_management: "Branch Management",
        manage_locations: "Manage your business locations and headquarters",
        add_new_branch: "Add New Branch",
        branch_name: "Branch Name",
        location_address: "Location / Address",
        contact_phone: "Contact Phone",
        set_as_main_hq: "Set as Main HQ?",
        main_headquarter: "Main Headquarter",
        setup_new_branch: "Setup New Branch",
        update_branch: "Update Branch",
        delete_branch_confirm: "Are you sure you want to delete this branch? This might affect linked data like orders and inventory.",
        table_qr_setup: "Table QR Setup",
        manage_table_qr: "Generate and manage unique QR codes for each table",
        add_table: "Add Table",
        table_number_name: "Table Number / Name",
        generate_table_qr: "Generate Table QR",
        view_qr: "View QR",
        print_qr_tag: "Print QR Tag",
        copy_link: "Copy Link",
        open_menu: "Open Menu",
        qr_status: "QR Status",
        ready: "READY",
        missing: "MISSING",
        remove_table_confirm: "This will permanently delete this table's QR setup.",
        confirm_delete: "Confirm Deletion",
        success: "Success",
        failed: "Failed",
        invalid_image_format: "Only image files are allowed",
        image_size_too_large: "Image size must be less than 2MB",
        user_management: "User Management",
        staff_identity: "Staff Identity",
        business_role: "Business Role",
        contact_branch: "Contact / Branch",
        access_status: "Access Status",
        management: "Management",
        active_branches: "Active Branches",
        total_personnel: "Total Personnel",
        regular_team: "Regular Team",
        expires: "Expires",
        staff_nodes: "Staff Nodes",
        lookup_placeholder: "Lookup by name/id...",
        new_staff_member: "New Staff Member",
        update_staff: "Update Staff",
        purge: "Purge",
        view_only: "View Only",
        permitted: "Permitted",
        suspended: "Suspended",
        all_staff: "All Staff",
        executives: "Executives",
        admins: "Admins",
        staff_limit_reached: "Staff limit reached for your plan",
        required: "is required",
        password_not_match: "Passwords do not match",
        user_role: "User Role",
        owner: "Owner",
        executive: "Executive",
        security_permissions: "Security & Permissions",
        security_permissions_desc: "Control what each user role can access across branches",
        select_user_role: "Select User Role",
        user_role_desc: "Permissions will apply to all users assigned to this role.",
        pick_role_placeholder: "Pick a role to configure",
        multi_branch_access: "Multi-Branch Access",
        multi_branch_access_desc: "Permissions defined here are universal across all branches. Staff will only see data for their assigned branch.",
        module_permissions: "Module Permissions",
        select_all: "Select All",
        permission_name: "Permission Name",
        navigation_path: "Navigation Path",
        upload: "Upload",
        yes: "Yes",
        no: "No",
        branch_management_desc: "Global control center for multi-branch operations and executive oversight.",
        staff_management_desc: "Manage your business team, roles, and administrative access.",
        password: "Password",
        report: "Report",
        pending_table: "Pending Table",
        sound_on: "Sound On",
        sound_off: "Sound Off",
        need_restock: "Need to re-stock",
        purchase_receipt: "Purchase Receipt",
        dine_in: "Dine In",
        take_away: "Take Away",
        customer_name: "Customer Name",
        table_label: "Table",
        order_list: "Order List",
        cart_empty: "Cart is empty",
        add_from_menu: "Add items from the menu",
        payment_details: "Payment Details",
        total_savings: "Total Savings",
        tax_fees: "Tax & Fees",
        select_payment: "Select payment",
        place_order: "Place Order",
        customize_coffee: "Customize Your Coffee",
        mood: "Mood",
        size: "Size",
        sugar_level: "Sugar Level",
        order_completed: "Order completed!",
        order_placed: "Order placed successfully!",
        new_order_received: "New order received from table!",
        hot: "Hot",
        ice: "Ice",
        available: "Available",
        pending_orders: "Pending Table Orders",
        no_pending: "No pending table orders",
        walk_in: "Walk-in",
        guest: "Guest",
        refresh_list: "Refresh List",
        unknown: "Unknown",
        no_discount: "No Discount",
        update: "Update",
        order_failed: "Order failed!",
        fetch_branch_failed: "Failed to fetch branches",
        fetch_table_failed: "Failed to fetch tables",
        operation_failed: "Operation failed",
        scan_menu_order: "Scan to view Menu & Order",
        recipe: "Recipe",
        audit: "Audit",
        off: "Off",
        update_item: "Update Item",
        save_item: "Save Item",
        choose_size: "Choose Size",
        label_required: "Label required",
        price_required: "Price required",
        category_required: "Category required",
        enter_description: "Enter product description",
        view: "View",
        performance_trends: "Performance Trends",
        top_selling_products: "Top Selling Products",
        system_distribution: "System Distribution",
        total_revenue_growth: "Total Revenue Growth",
        customer_retention: "Customer Retention",
        not_specified: "Not Specified",
        no_phone: "No Phone",
        create_branch: "Create Branch",
        free_plan_limit: "Free Plan users are limited to 1 branch. Upgrade to Pro for multi-location support.",
        pro_plan_info: "You are on the Pro Plan. You can manage multiple branches seamlessly.",
        goods_received_success: "Goods received and stock updated!",
        create_purchase_failed: "Failed to create purchase",
        receive_goods_failed: "Failed to receive goods",
        something_went_wrong: "Something went wrong",
        confirm_remove_raw_material: "Are you sure you want to remove this raw material?",
        no_image: "No Img",
        khqr_setting: "KHQR Setting",
        upload_khqr: "Upload KHQR",
        khqr_image: "KHQR Image",
        daily_closing_title: "Daily Closing & Orders",
        daily_closing_desc: "Review daily sales and reconcile your accounts",
        total_orders_label: "Total Orders",
        dash_cash: "Cash",
        dash_aba: "ABA / QR",
        dash_wing: "Wing / Others",
        top_selling_label: "Top Selling",
        tab_today: "Today/Closing",
        tab_history: "Shift History",
        add_expense_btn: "Add Expense",
        save_print_report: "Save & Print Shift Report",
        open_shift_btn: "Open Shift",
        opening_cash_label: "Opening Cash",
        opening_cash_sub: "Initial Balance",
        actual_cash_label: "Actual Cash in Hand",
        cash_in_drawer: "Cash in Drawer",
        cash_sales_label: "Cash Sales",
        cash_expenses_label: "Cash Expenses",
        exchange_rate_label: "Exchange Rate",
        remark_placeholder: "Remark / Notes (e.g. customer owes, missing change...)",
        difference_label: "Difference",
        expected_label: "Expected",
        orders_this_shift: "Orders for this shift",
        refresh_btn: "Refresh",
        close_date: "Close Date",
        staff_role_label: "Staff / Role",
        actual_in_drawer: "Actual In Drawer",
        total_sales_all: "Total Sales (All)",
        order_detail_title: "Enhanced Order Detail",
        order_summary: "Order Summary",
        items_ordered: "Items Ordered",
        quick_expense_title: "Quick Expense",
        expense_amount: "Expense Amount",
        payment_type: "Payment Type",
        expense_cash_desc: "Cash / From Drawer",
        expense_bank_desc: "Bank / QR (Doesn't affect cash)",
        describe_expense: "Describe the expense (e.g. Bought ice)",
        open_new_shift: "Open New Shift",
        enter_opening_cash: "Enter your opening cash to start",
        authorized_by: "Authorized By",
        open_shift_now: "Open Shift Now",
        home_boutique: "Boutique",
        discover: "Discover",
        starred: "Starred",
        profile_atelier: "Atelier",
        selected_collections: "Selected collections",
        house_favorites: "House Favorites",
        pure_perfection: "Pure perfection in every cup",
        taste_luxury: "Taste the Luxury of",
        fine_beans: "Fine Beans",
        signature_limited: "Experience our signature limited edition brew, curated for premium members.",
        explore_now: "Explore Now",
        search_product: "Discover your coffee...",
        search_results: "Found for You",
        related_products: "You Might Also Like",
        established: "Established",
        basket_empty: "Basket is currently empty",
        your_basket: "Your Basket",
        place_order_now: "Place Order Now",
        subview_history: "Order History",
        subview_settings: "App Settings",

        accounting_class: "Accounting Class",
        cogs: "COGS (Stock/Materials)",
        operational: "Operational (OpEx)",
        administrative: "Administrative",
        stock_audit_correction: "Stock Audit & Correction",
        transfer_status: "Transfer Status",
        transfer_ref: "Transfer Ref",
        from_branch: "From Branch",
        to_branch: "To Branch",
        stock_transfer_details: "Stock Transfer Details",
        stock_ledger_audit: "Stock Ledger & Audit",
        stock_to_stock_transfers: "Store-to-Store Transfers",
        new_transfer_req: "New Stock Transfer Request",
        transfer_note: "Transfer Note",
        source_branch: "Source Branch",
        recipient_branch: "Recipient Branch",
        accept_add_stock: "Accept & Add to Stock",
        confirm_goods_receipt: "Confirm Goods Receipt",
        cancel_transfer_confirm: "Stock will be returned to the origin branch.",
        add_another_item: "Add Another Item",
        cannot_transfer_same_branch: "Cannot transfer to the same branch. Please select a different recipient branch.",
        validation_error: "Validation Error",
        ok_btn: "OK",
        cancel_btn: "Cancel",
        authorized_by: "Authorized By",
        discard: "Discard",
        submit_audit: "Submit Audit",
        inventory_movement: "Inventory Movement",
        qty_in_stock: "Qty in Stock",
        no_ingredients_defined: "No ingredients defined yet",
        select_product_to_view_recipe: "Select a product to view or manage its recipe",
        please_select_ingredient: "Please select an ingredient",
        search_ingredients: "Search ingredients...",
        please_enter_qty: "Please enter quantity",
        save_success: "Saved successfully",
        cost_per_unit: "Cost/Unit",
        total_cost: "Total Cost",
        recipe_total_cost: "Total Recipe Cost",
        current_stock: "In Stock",
        batch_no: "Batch #",
        expiry_date: "Expiry Date",
        tax: "Tax",
        payment_method: "Payment Method",
        cash: "Cash",
        bank: "Bank / Transfer",
        discount_full: "Discount Amount",
        grand_total: "Grand Total",
        unit: "Unit",
        sign_in: "Sign In",
        language: "Language",
        favorites: "Favorites",
        starred: "Starred",
        home: "Home",
        your_basket: "Your Basket",
        basket_empty: "Basket is currently empty",
        place_order_now: "Place Order Now",
        search_in_category: "Search in",
        category_label: "Category",
        no_results_found: "No results found",
        waiting_for_cashier: "Waiting for Cashier",
        brewing_cooking: "Brewing / Cooking",
        ready_pickup: "Ready for Pickup",
        served_enjoy: "Served & Enjoy",
        pending_status_desc: "Your order is being reviewed by the cashier.",
        cooking_status_desc: "Our barista is crafting your perfect cup.",
        ready_status_desc: "Your coffee is ready! Please collect it at the counter.",
        served_status_desc: "Enjoy your drink! Hope to see you again soon.",
        history: "History",
        no_orders_found: "No orders found",
        settings: "Settings",
        orders: "Orders",
        profile: "Profile",
        add_to_basket: "Add to Basket",
        order_checkout: "Order Checkout",
        service_fee: "Service Fee",
        free: "Free",
        placing_order: "Placing Order...",
        unit_price: "Unit Price",
        back_to_home: "Back to Home",
        order_received: "Order Received",
        guest: "Guest",
        order_success_msg: "Order Placed Successfully! Barista is preparing your coffee. ☕",
        order_failed_msg: "Failed to place order.",
        order_status_update_failed: "Order placed, but failed to update status.",
        premium_experience: "Premium Experience",
        hi: "Hi",
        special_offer: "Special Offer",
        fresh_brewed: "Fresh Brewed",
        happiness: "Happiness",
        hurry_up: "Hurry! Offer ends in 2 hours",
        browse_mode: "Browsing Mode",
        browse_mode_msg: "You are currently viewing the menu. Please scan the QR code on your table to place an order.",
        scan_to_order: "Scan QR to Order",
        please_scan_msg: "Please scan the QR code at your table to start your coffee journey.",
        select_branch_to_browse: "Or select a branch to browse",
        staff_portal: "Staff Portal",
        ready_to_serve: "Ready to Serve",
        no_branch_selected: "No Branch Selected",
        stock_valuation: "Stock Valuation",
        expiring_soon: "Expiring Soon",
        stock_insights: "Stock Insights",
        total_items: "Total Items",
        reorder_needed: "Reorder Needed",
        view_inventory: "View Inventory",
        financial_trend: "Financial Trend",
        live_summary_today: "Live Summary (Today)",
        todays_income: "Today's Income",
        todays_expense: "Today's Expense",
        net_daily_profit: "Net Daily Profit",
        period_revenue: "Period Revenue",
        period_expenses: "Period Expenses",
        avg_cost: "Avg Cost",
        par_level: "Par Level (Max)",
        min_alert: "Min Alert",
        product_category_header: "Product & Category",
        unit_price_header: "Unit Price",
        stock_header: "Stock",
        table_dashboard: "Table Dashboard",
        free_status: "FREE",
        occupied_status: "OCCUPIED",
        available_status: "AVAILABLE",
        people_count: "People",
        shift_started: "Shift Started",
        close_shift: "Close Shift",
        discover_placeholder: "Discover your coffee or snack...",
        held_drafts: "Held Drafts",
        grid_view: "Grid",
        list_view: "List",
        sync_btn: "Sync",
        full_screen: "Full Screen",
        purchase_receipt_header: "PURCHASE RECEIPT",
        sent_status: "Sent",
        save_btn: "Save",
        order_items_label: "ORDER ITEMS",
        subtotal_label: "SUBTOTAL",
        discount_label: "DISCOUNT",
        total_label: "TOTAL",
        khr_label: "KHR",
        general_settings_desc: "Manage your business information and Point of Sale configurations",
        business_info_header: "Business Information",
        business_name_label: "Business Name",
        owner_name_label: "Owner Name",
        phone_number_label: "Phone Number",
        email_address_label: "Email Address",
        address_label: "Address",
        website_url_label: "Website / URL",
        pos_financial_config_header: "POS & Financial Config",
        currency_symbol_label: "Currency Symbol",
        exchange_rate_label: "Exchange Rate (1 USD = ? KHR)",
        vat_tax_label: "VAT / TAX (%)",
        service_charge_label: "Service Charge (%)",
        save_all_changes_btn: "Save All Changes",
        open_shift_now_btn: "Open Shift Now",
        mobile_app_promo_tab: "Mobile App & Promo",
        promo_banner_header: "Home Banner Promotion",
        promo_active_status: "Active Status",
        promo_tag_label: "Promo Tag (e.g. Grand Opening)",
        promo_title_label: "Banner Title",
        promo_desc_label: "Banner Description",
        promo_image_label: "Banner Background Image URL",
        global_discount_header: "Global Percentage Discount",
        discount_scope_label: "Discount Scope",
        buy_x_get_y_header: "Promotion Engine: Buy X Get Y",
        promo_scope_label: "Promotion Scope",
        start_date_label: "Start Date",
        end_date_label: "End Date",
        category_tab: "Category Management",
        printing_workflow_header: "Printing Workflow Configuration",
        auto_print_label: "Auto Print on Checkout",
        auto_print_desc: "Automatically trigger print dialog after each sale",
        execution_order_header: "Execution Order",
        print_priority_label: "Which should print first?",
        label_first_option: "Label (Sticker) First",
        invoice_first_option: "Invoice (Receipt) First",
        doc_availability_header: "Document Availability",
        enable_invoice_label: "Enable Customer Invoice",
        enable_label_stickers: "Enable Cup Labels (Stickers)",
        enable_kitchen_ticket: "Enable Kitchen Ticket (Order Send)",
        pro_tip_label: "Pro Tip",
        kds_header: "KDS - Kitchen Display System",
        history_btn: "History",
        refresh_btn: "Refresh",
        auto_refresh_on: "Auto-Refresh: ON",
        auto_refresh_off: "Auto-Refresh: OFF",
        takeaway_label: "Takeaway",
        dine_in_label: "Dine-In",
        pending_status: "PENDING",
        preparing_status: "PREPARING",
        done_status: "DONE",
        start_preparing_btn: "Start Preparing",
        finish_preparing_btn: "Finish",
        kds_history_title: "KDS History (Today)",
        show_active_btn: "Show Active",
        mark_ready_btn: "Mark Ready",
        mark_served_btn: "Mark Served",
        served_today_empty: "No served orders today",
        active_tickets_empty: "No active preparation tickets",
        balanced_status: "Balanced",
        discrepancy_status: "Discrepancy",
        status_label: "STATUS",
        print_receipt_btn: "Print Receipt",
        scan_barcode_placeholder: "Scan Barcode or Type...",
        camera_btn: "Camera",
        close_camera_btn: "Close",
        receive_now_label: "Receive Now",
        confirm_receiving_btn: "Confirm Receiving",
        batch_label: "Batch",
        expiry_label: "Expiry",
        order_qty_label: "Order",
        rec_qty_label: "Rec",
        product_label: "Product",
        unit_label: "Unit",
        select_date_placeholder: "Select date",
        show_all_btn: "Show All",
        save_receiving_btn: "Save Receiving",
        invoice_placeholder: "Invoice #",
        cash_method: "Cash",
        bank_method: "Bank",
        request_status: "Request",
        pending_status_simple: "Pending",
        received_status: "Received",
        product_list_header: "PRODUCT LIST",
        quantity_label: "QUANTITY",
        cost_price_label: "COST PRICE",
        unit_pcs: "Pcs",
        unit_box: "Box",
        unit_case: "Case",
        available_products: "AVAILABLE PRODUCTS",
        raw_materials_ledger: "RAW MATERIALS",
        product_alerts: "PRODUCT ALERTS",
        ingredient_alerts: "INGREDIENT ALERTS",
        items_low: "Items Low",
        stock_ledger_audit_desc: "Transparency for every inventory movement across the network",
        date_and_time_label: "DATE & TIME",
        item_category_label: "ITEM CATEGORY",
        item_name_label: "ITEM NAME",
        transaction_label: "TRANSACTION",
        change_label: "CHANGE",
        balance_label: "BALANCE",
        authorized_by_label: "AUTHORIZED BY",
        reason_remark_label: "REASON / REMARK",
        sale_label: "SALE",
        movements_found: "movements found",
        close_shift_title: "Close Shift",
        sales_summary_label: "Sales Summary",
        cash_sales_label: "Cash Sales ($)",
        aba_payments_label: "ABA Payments ($)",
        wing_payments_label: "Wing Payments ($)",
        total_sales_label: "Total Sales",
        total_expenses_label: "Total Expenses",
        cash_counting_label: "Cash Counting",
        expected_in_drawer_label: "EXPECTED CASH IN DRAWER",
        actual_cash_usd_label: "ACTUAL CASH (USD)",
        actual_cash_khr_label: "ACTUAL CASH (KHR)",
        total_variance_label: "TOTAL VARIANCE (USD)",
        remark_placeholder: "Any notes about this shift...",
        confirm_close_shift_btn: "Confirm Close Shift",
        basic_details_title: "Basic Details",
        inventory_media_title: "Inventory & Media",
        cooking_options_title: "Cooking & Options",
        taste_instructions_label: "Taste / Special Instructions",
        portions_sizes_label: "Portions / Sizes",
        side_dishes_extras_label: "Side Dishes / Extras",
        medical_specs_title: "Medical Specifications",
        generic_name_label: "Generic Name (Chemical)",
        strength_label: "Strength (mg/ml)",
        medical_note: "Note: These details appear on prescription labels and for expiry tracking.",
        packaging_units_label: "Packaging / Units",
        dosage_instructions_label: "Usage / Dosage Instructions",
        price_per_size_msg: "Price per size overrides the base price",
        medical_info_label: "Medical Info",
        expiry_column_label: "Expiry",
        recipe_config_title: "Recipe Configuration",
        est_cost_per_cup: "Est. Cost Per Cup",
        selling_price_label: "Selling Price",
        gross_profit_label: "Gross Profit",
        select_ingredient_label: "Select Ingredient",
        usage_qty_label: "Usage Qty",
        add_ingredient_link: "Add New Ingredient Link",
        sync_recipe_btn: "Sync Recipe",
        profit_margin: "Profit Margin",
        value_stock_label: "Value & Stock",
        in_stock_label: "in stock",
        ready_to_serve_label: "Ready to Serve",
        made_to_order_label: "Recipe Base",
        recipe_tooltip: "Recipe / Ingredients",
        physical_stock_audit: "Physical Stock Audit",
        start_new_audit: "Start New Physical Audit",
        extra_stock_label: "Extra Stock",
        missing_stock_label: "Missing Stock",
        audit_commit_confirm: "Confirm and update stock levels?",
        audit_commit_confirm_desc: "This will create {n} automatic adjustments to match physical counts.",
        audit_instructions: "Select a category to begin a physical stock count. The system will help you identify discrepancies and update the inventory records.",
        audit_product_title: "Product Inventory Audit",
        audit_material_title: "Raw Material Audit",
        audit_items_count: "Reviewing {n} items",
        system_qty_label: "System QTY",
        physical_count_label: "Physical Count",
        variance_label: "Variance",
        audit_success_msg: "Audit complete! Updated {successCount}/{total} discrepancies.",
        no_variance_msg: "No variances found. Everything is accurate!",
        complete_commit_btn: "Complete & Commit Audit",
        stock_intelligence_title: "Stock Intelligence & Forecasting",
        days_left_label: "Est. Days Remaining",
        run_out_date_label: "Run-out Date",
        replenish_urgent: "Action Required: Replenish Soon",
        stock_health_good: "Stock Level Healthy",
        avg_daily_usage: "Avg. Daily Usage",
        adjust_now_btn: "Adjust Now",
        go_to_purchase: "Go to Purchase",
        stock_adj_desc: "Adjust inventory manually due to error, breakage, or physical auditing.",
        finished_product_opt: "Finished Product",
        raw_material_opt: "Raw Material",
        qty_adj_placeholder: "e.g. 10 to add, -5 to remove",
        reason_placeholder: "Select common reason...",
        remark_optional: "Custom Remark (Optional)",
        profit_analysis_title: "Profit Analysis & Menu Engineering",
        menu_engineering_label: "Menu Categorization",
        star_item_label: "Star (Best Performing)",
        plowhorse_item_label: "Plowhorse (High Volume, Low Margin)",
        puzzle_item_label: "Puzzle (High Margin, Low Volume)",
        dog_item_label: "Dog (Poor Performance)",
        margin_per_unit: "Margin per Unit",
        total_contribution: "Total Profit Contribution",
        popularity_rank: "Popularity Rank",
        rec_star: "Highly Profitable! Recommend Featured Promotion.",
        rec_plowhorse: "Popular but Low Margin. Consider reducing ingredient costs.",
        rec_puzzle: "Great Profit but Low Sales. Try bundling or special promos.",
        rec_dog: "Poor performance. Consider removing or redesigning.",
        reason_barista_error: "Barista Error (Wrong Make/Taste)",
        reason_spillage: "Spillage / Product Dropped",
        reason_expired: "Item Expired",
        reason_sampling: "Customer Sampling",
        reason_store_use: "Internal Store Use",
        reason_correction: "General Stock Correction",
        in_stock_badge: "in stock",
        shift_audit_title: "Shift Closing & Cash Audit",
        expected_cash_label: "Expected Cash (System)",
        actual_cash_label: "Actual Counted Cash",
        cash_variance_label: "Cash Variance (+/-)",
        shift_report_summary: "Shift Report Summary",
        opening_cash_label: "Opening Cash",
        total_sales_cash: "Total Cash Sales",
        total_sales_online: "Total Online/Card Sales",
        closing_note_placeholder: "Any remarks for this shift closing?",
        business_insights_title: "Business Health & Insights",
        net_sales_label: "Net Sales Today",
        order_count_label: "Total Orders",
        avg_order_value: "Avg. Spend / Order",
        peak_hours_analysis: "Peak Hours Intelligence",
        category_mix_label: "Category Sales Mix",
        busiest_time_label: "Busiest Time",
        sales_trend_label: "Hourly Sales Trend",
        morning_briefing: "Executive Morning Briefing",
        morning_briefing_desc: "Here is your business summary from yesterday",
        yesterday_revenue: "Yesterday Revenue",
        yesterday_profit: "Yesterday Net Profit",
        top_performer: "Top Performer",
        best_selling_item: "Best Selling Item",
        new_vips: "New VIP Members",
        digital_receipt_title: "Digital Receipt",
        scan_to_view: "Scan to view in phone",
        done_btn: "Done / រួចរាល់",
        loyalty_portal: "Loyalty Portal",
        menu_board_label: "Digital Menu Board",
        waste_label: "Waste & Damage Tracker",
        forecast_label: "AI Ingredient Forecast",
        marketing_label: "Marketing & CRM",
        kds_label: "Kitchen Display System (KDS)",
        performance_label: "Staff Performance & Commissions",
        menu_group_marketing: "Marketing & CRM",
    },
    kh: {
        menu_group_main: "ប្រតិបត្តិការចម្បង",
        menu_group_marketing: "ទីផ្សារ និង ទំនាក់ទំនងអតិថិជន",
        menu_group_inventory: "ការគ្រប់គ្រងស្តុក",
        menu_group_setup: "ការរៀបចំទូទៅ",
        menu_group_admin: "រដ្ឋបាល និងសិទ្ធិបុគ្គលិក",
        menu_group_reports: "របាយការណ៍អាជីវកម្ម",

        dashboard: "ផ្ទាំងគ្រប់គ្រង",
        subscription: "គម្រោងប្រើប្រាស់",
        inventory: "ស្តុកទំនិញ",
        purchases: "ទិញទំនិញចូល",
        suppliers: "អ្នកផ្គត់ផ្គង់",
        stock: "ស្តុក",
        stock_logs: "ប្រវត្តិកែសម្រួលស្តុក",
        stock_transfer: "ផ្ទេរស្តុកទំនិញ",
        pos: "ការលក់ (POS)",
        branches: "សាខានីមួយៗ",
        tables: "តុក និង កូដ QR",
        products: "មុខទំនិញ",
        categories: "ប្រភេទមុខទំនិញ",
        kds: "ផ្ទះបាយ (KDS)",
        order_history: "ប្រវត្តិនៃការកុម្ម៉ង់",
        staff_roles: "បុគ្គលិក និងសិទ្ធិ",
        users: "បុគ្គលិក",
        roles: "មុខដំណែង",
        permissions: "សិទ្ធិប្រើប្រាស់",
        plans: "ជម្រើសគម្រោង",
        reports: "របាយការណ៍",
        sales_report: "របាយការណ៍លក់",
        expenses: "ការចំណាយ",
        best_sellers: "ទំនិញលក់ដាច់",
        settings: "ការកំណត់",
        business: "ប្រព័ន្ធអាជីវកម្ម",
        service_blueprints: "កញ្ចប់មុខងារសេវាកម្ម",
        system_modules: "មុខងារបន្ថែម",
        logout: "ចាកចេញ",
        profile: "ព័ត៌មានផ្ទាល់ខ្លួន",
        executive_dashboard: "ផ្ទាំងគ្រប់គ្រងព័ត៌មានសង្ខេប",
        real_time_metrics: "ទិន្នន័យលក់ និងដំណើរការអាជីវកម្មសរុប",
        marketing_title: "ប្រព័ន្ធទីផ្សារវៃឆ្លាត និង CRM",
        marketing_subtitle: "ស្វែងរក និងទាក់ទាញអតិថិជនសំខាន់ៗឱ្យត្រឡប់មកវិញ។",
        inactive_vips: "សមាជិក VIP ដែលអសកម្ម (>៣០ ថ្ងៃ)",
        total_loyalty: "សមាជិកសរុប",
        recovery_rate: "អត្រាទាញយកអតិថិជនមកវិញ",
        at_risk_customers: "អតិថិជនដែលមានហានិភ័យបាត់បង់",
        refresh_analysis: "វិភាគឡើងវិញ",
        all_loyalty_members: "សមាជិកទាំងអស់",
        win_back_campaign: "យុទ្ធនាការទាក់ទាញអតិថិជនមកវិញ",
        suggested_offer: "ការផ្តល់ជូនដែលបានណែនាំ",
        send_promotion: "ផ្ញើការផ្តល់ជូន",
        win_back: "ទាក់ទាញមកវិញ",
        days_inactive: "ចំនួនថ្ងៃអសកម្ម",
        apply_filters: "ប្រើប្រាស់ចម្រោះ",
        search: "ស្វែងរក",
        recent_activity: "សកម្មភាពថ្មីៗ",
        view_all_orders: "មើលការកុម្ម៉ង់ទាំងអស់",
        no_data: "មិនមានទិន្នន័យ",
        customer_overview: "ទិដ្ឋភាពអតិថិជន",
        financial_summary: "សង្ខេបហិរញ្ញវត្ថុ",
        sales_performance: "លទ្ធផលនៃការលក់",
        total: "សរុប",
        loyalty_subtitle: "ស្វែងរក និងគ្រប់គ្រងសមាជិក VIP របស់អ្នកយ៉ាងងាយស្រួល",
        find_member: "ស្វែងរកសមាជិក",
        enter_card_phone: "សូមបញ្ចូលលេខកាតសមាជិក ឬលេខទូរស័ព្ទខាងក្រោម",
        search_placeholder: "ស្វែងរកតាមលេខកាត ឬលេខទូរស័ព្ទ...",
        active_tiers: "កម្រិតសមាជិកសកម្ម",
        levels: "កម្រិត",
        prepaid_wallet: "កាបូបលុយត្រៀមបង់",
        no_recent_searches: "មិនមានការស្វែងរកថ្មីៗទេ",
        please_enter_card_phone: "សូមបញ្ចូលលេខកាត ឬលេខទូរស័ព្ទ!",
        total_sales: "លក់សរុប",
        total_expenses: "ចំណាយសរុប",
        net_profit: "ចំណេញសុទ្ធ",
        tier: "កម្រិតសមាជិក",
        last_visit: "ចូលទិញចុងក្រោយ",
        never: "មិនដែល",
        member: "សមាជិក",
        points: "ពិន្ទុ",
        order_count: "ចំនួនកុម្ម៉ង់",
        kds_subtitle: "គ្រប់គ្រងការកុម្ម៉ង់បច្ចុប្បន្ន និងល្បឿនឆុងកាហ្វេ",
        active_orders: "ការកុម្ម៉ង់កំពុងដើរ",
        no_active_orders: "មិនមានការកុម្ម៉ង់ដែលសកម្មទេ សម្រាកញ៉ាំកាហ្វេបន្តិចទៅ!",
        no_kds_history: "មិនមានប្រវត្តិសម្រាប់ថ្ងៃនេះទេ",
        start_btn: "ចាប់ផ្តើម",
        ready_btn: "រួចរាល់",
        done_btn: "រួចរាល់សព្វគ្រប់",
        avg_transaction: "មធ្យមភាគលក់",
        waste_title: "ការតាមដានទំនិញខូចខាត និងបាត់បង់",
        waste_subtitle: "តាមដាន និងកត់ត្រាការបាត់បង់ទំនិញ ដើម្បីការពារប្រាក់ចំណេញរបស់អ្នក។",
        record_waste: "កត់ត្រាទំនិញខូចខាត",
        total_items_wasted: "ទំនិញខូចខាតសរុប",
        record_new_waste: "កត់ត្រាទំនិញខូចខាត/បាត់បង់ថ្មី",
        record_now: "កត់ត្រាឥឡូវនេះ",
        select_item_type: "ជ្រើសរើសប្រភេទ",
        finished_product: "ទំនិញសម្រេច",
        raw_material_ingredient: "វត្ថុធាតុដើម / គ្រឿងផ្សំ",
        expired: "ហួសកំណត់",
        damaged: "បែកបាក់ / ខូចខាត",
        wrong_recipe: "ធ្វើខុសបច្ចេកទេស",
        profit_margin: "ភាគរយចំណេញ",
        forecast_title: "ការទស្សន៍ទាយវត្ថុធាតុដើមដោយ AI",
        forecast_subtitle: "យោងតាមការលក់របស់អ្នកក្នុងរយៈពេល ៧ ថ្ងៃចុងក្រោយ នេះគឺជាអ្វីដែលអ្នកត្រូវការសម្រាប់សប្តាហ៍ក្រោយ។",
        export_purchase_list: "ទាញចេញបញ្ជីទិញទំនិញ",
        supply_demand_analysis: "ការវិភាគការផ្គត់ផ្គង់ និងតម្រូវការ",
        forecast_confidence: "ភាពជឿជាក់នៃការទស្សន៍ទាយ",
        avg_daily_usage: "ការប្រើប្រាស់មធ្យមប្រចាំថ្ងៃ",
        next_7_days_expected: "រំពឹងទុកសម្រាប់ ៧ ថ្ងៃបន្ទាប់",
        suggested_purchase: "ការផ្តល់ជូនទិញ",
        sufficient: "គ្រប់គ្រាន់",
        no_forecast_data: "មិនទាន់មានទិន្នន័យលក់គ្រប់គ្រាន់ដើម្បីបង្កើតការទស្សន៍ទាយនៅឡើយទេ។",
        expected_usage_7d: "ការប្រើប្រាស់រំពឹងទុក (៧ ថ្ងៃ)",
        forecast_recommendation: "ការណែនាំ៖ ពិចារណាទិញទំនិញដែលបានសម្គាល់ពណ៌មាស មុនថ្ងៃច័ន្ទ។",
        performance_trends: "និន្នាការលទ្ធផល",
        revenue: "ចំណូល",
        growth: "កំណើន",
        distribution: "ការបែងចែក",
        live: "បច្ចុប្បន្ន",
        now: "អម្បាញ់មិញ",
        account_settings: "ការកំណត់គណនី",
        general_info: "ព័ត៌មានទូទៅ",
        full_name: "ឈ្មោះពេញ",
        email_address: "អុីមែល (Login ID)",
        security_settings: "ការកំណត់សុវត្ថិភាព",
        new_password: "លេខសម្ងាត់ថ្មី",
        confirm_password: "បញ្ជាក់លេខសម្ងាត់",
        leave_blank: "ទុកឱ្យនៅទទេប្រសិនបើមិនផ្លាស់ប្តូរ",
        save_changes: "រក្សាទុក",
        active_account: "គណនីសកម្ម",
        branch: "សាខា",
        business_label: "អាជីវកម្ម",
        order_no: "លេខកុម្ម៉ង់",
        date: "កាលបរិច្ឆេទ",
        status: "ស្ថានភាព",
        amount: "ចំនួនទឹកប្រាក់",
        payment_method: "ការទូទាត់",
        cashier: "អ្នកគិតលុយ",
        all: "ទាំងអស់",
        pending: "រង់ចាំ",
        paid: "បង់រួច",
        cancelled: "បោះបង់",
        view_details: "មើលលម្អិត",
        order_details: "លម្អិតការកុម្ម៉ង់",
        subtotal: "សរុបរង",
        tax: "ពន្ធ",
        discount: "បញ្ចុះតម្លៃ",
        print: "បោះពុម្ព",
        export: "ទាញយក",
        filter: "ចម្រោះ",
        items: "មុខ",
        no_orders: "រកមិនឃើញការកុម្ម៉ង់ទេ",
        order_management: "គ្រប់គ្រងការកុម្ម៉ង់",
        track_orders: "តាមដាន និងគ្រប់គ្រងការកុម្ម៉ង់របស់អ្នកឱ្យមានប្រសិទ្ធភាព",
        avg_order_value: "តម្លៃមធ្យមកុម្ម៉ង់",
        this_month: "ខែនេះ",
        total_revenue: "ចំណូលសរុប",
        subscription_limits: "ការជាវ និងដែនកំណត់របស់ខ្ញុំ",
        overview: "ទិដ្ឋភាពទូទៅ",
        billing_history: "ប្រវត្តិនៃការបង់ប្រាក់",
        current_trial: "ការសាកល្បងបច្ចុប្បន្ន",
        current_package: "កញ្ចប់បច្ចុប្បន្ន",
        package_30_day_trial: "សាកល្បងប្រើ ៣០ថ្ងៃ",
        started: "ចាប់ផ្តើមនៅ",
        expires_on: "ផុតកំណត់នៅ",
        no_expiry: "គ្មានថ្ងៃផុតកំណត់",
        days_remaining: "ថ្ងៃនៅសល់",
        days_ago: "ថ្ងៃមុន",
        expired_label: "ផុតកំណត់",
        upgrade_plan: "ដំឡើងគម្រោង",
        resource_utilization: "ការប្រើប្រាស់ធនធាន",
        staff_seats: "ចំនួនបុគ្គលិក",
        store_branches: "ចំនួនសាខា",
        sku_capacity: "ចំនួនមុខទំនិញ (Products)",
        unlimited: "មិនកំណត់",
        need_more_capacity: "ត្រូវការបន្ថែមមែនទេ? ការដំឡើងចំណាយពេលតិចជាង ១ នាទី។",
        compare_plans: "ប្រៀបធៀបគម្រោង",
        subscription_history: "ប្រវត្តិនៃការជាវ",
        history_desc: "រាល់រយៈពេលនៃការជាវកន្លងមក និងបច្ចុប្បន្នរបស់អ្នក។",
        refresh: "ផ្ទុកឡើងវិញ",
        price: "តម្លៃ",
        duration: "រយៈពេល",
        not_available: "មិនអាចប្រើបាន",
        current: "បច្ចុប្បន្ន",
        maybe_later: "ទុកពេលក្រោយ",
        next_confirm: "បន្ទាប់៖ បញ្ជាក់ការដំឡើង →",
        currently_active: "កំពុងប្រើប្រាស់",
        upgrade_picker_desc: "ជ្រើសរើសគម្រោងដែលសាកសមនឹងតម្រូវការអាជីវកម្មរបស់អ្នក។ សិទ្ធិ និងដែនកំណត់នឹងត្រូវបានធ្វើបច្ចុប្បន្នភាពភ្លាមៗ។",
        upgrading_to: "កំពុងដំឡើងទៅ",
        month: "ខែ",
        relogin_required: "តម្រូវឱ្យចូលគណនីម្តងទៀត",
        relogin_desc: "សូមចាកចេញ និងចូលគណនីម្តងទៀត ដើម្បីដំណើរការសិទ្ធិ និងមុខងារថ្មីៗរបស់អ្នក។",
        upgrade_success: "ការដំឡើងបានជោគជ័យ! 🎉",
        full_access_to: "ឥឡូវនេះអ្នកមានសិទ្ធិចូលប្រើពេញលេញទៅកាន់",
        active_until: "មានសុពលភាពរហូតដល់",
        got_it: "យល់ព្រម! 🚀",
        days: "ថ្ងៃ",
        one_time: "ការទិញផ្តាច់",
        lifetime: "ផ្តាច់",
        permanent_access: "ប្រើប្រាស់ជារៀងរហូត",
        upgrade: "ដំឡើង",
        pro_label: "អាជីព (PRO)",
        premium_label: "ខ្ពស់ (PREMIUM)",
        main_branch: "សាខាធំ",
        admin_label: "រដ្ឋបាល",
        staff_label: "បុគ្គលិក",
        subscription_details: "ព័ត៌មានការជាវ",
        estimated_servings_label: "ចំនួនកែវសរុប (ប៉ាន់ស្មាន)",
        real_time_price: "តម្លៃបច្ចុប្បន្ន រួមទាំងការខ្ជះខ្ជាយ",
        low_stock_warning: "គ្រឿងផ្សំខ្លះជិតអស់ពីស្តុក! សូមត្រួតពិនិត្យ និងទិញបន្ថែម។",
        after_waste: "ក្រោយការខ្ជះខ្ជាយ",
        estimated_cost_per_cup: "ថ្លៃដើមក្នុង ១ កែវ (ប៉ាន់ស្មាន)",
        will_deduct: "នឹងដក",
        from_stock: "ពីស្តុក",
        waste_factor_desc: "ភាគរយខ្ជះខ្ជាយ — បរិមាណបន្ថែមដែលត្រូវដកចេញពីស្តុកដោយសារការហៀរ ឬបាត់បង់។",
        effective_qty: "ប្រើប្រាស់ពិត",
        size: "ទំហំ",
        low_stock: "ស្តុកជិតអស់!",
        select_material: "ជ្រើសរើសសម្ភារ...",
        gram: "ក្រាម",
        cups: "កែវ",
        cost_per_cup: "ថ្លៃដើមក្នុង ១ កែវ",
        hide_header: "លាក់ក្បាលទំព័រ",
        show_header: "បង្ហាញក្បាលទំព័រ",
        product_list: "បញ្ជីមុខទំនិញ",
        add_new_product: "បន្ថែមមុខទំនិញថ្មី",
        edit_product: "កែសម្រួលមុខទំនិញ",
        search_product: "ស្វែងរកមុខទំនិញ...",
        product_name: "ឈ្មោះមុខទំនិញ",
        category_name: "ឈ្មោះប្រភេទ",
        quantity: "បរិមាណ",
        barcode: "បាកូដ",
        description: "ការពិពណ៌នា",
        image: "រូបភាព",
        action: "សកម្មភាព",
        confirm_delete_product: "តើអ្នកពិតជាចង់លុបមុខទំនិញនេះមែនទេ?",
        product_deleted: "បានលុបមុខទំនិញដោយជោគជ័យ",
        product_saved: "បានរក្សាទុកមុខទំនិញដោយជោគជ័យ",
        remove_data: "លុបទិន្នន័យ",
        confirm_remove_product: "តើអ្នកពិតជាចង់លុបមុខទំនិញនេះមែនទេ?",
        total_products: "មុខទំនិញសរុប",
        menu_inventory: "បញ្ជីមុខទំនិញលក់",
        add_new: "បន្ថែមថ្មី",
        brand: "ម៉ាក",
        edit_product_title: "☕ កែសម្រួលមុខទំនិញ",
        new_menu_item: "☕ បន្ថែមម្ហូប/ភេសជ្ជៈថ្មី",
        sizes: "ទំហំ",
        add_size: "បន្ថែមទំហំ",
        addons: "គ្រឿងបន្ថែម",
        add_addon: "បន្ថែមគ្រឿងបន្ថែម",
        customize_coffee: "ការកំណត់ជម្រើសបន្ថែម",
        mood: "ប្រភេទ / Mood",
        hot: "ក្តៅ",
        iced: "ត្រជាក់",
        frappe: "ក្រឡុក",
        sizes_override_msg: "* ប្រសិនបើមានកំណត់តម្លៃតាមទំហំខាងក្រោម វានឹងប្រើជំនួសតម្លៃគោលក្នុង POS (Sizes override Base Price).",
        base_price_label: "តម្លៃគោល",
        save_item: "រក្សាទុកទំនិញ",
        update_item: "កែសម្រួលទំនិញ",
        purchase: "ការទិញ",
        received: "បានទទួល / បញ្ចប់",
        request: "ស្នើសុំទិញ",
        invoice_no: "លេខវិក្កយបត្រ",
        supplier: "អ្នកផ្គត់ផ្គង់",
        raw_material: "វត្ថុធាតុដើម",
        recipe: "ការគ្រប់គ្រងរូបមន្ត",
        ingredients: "គ្រឿងផ្សំ",
        add_ingredient: "បន្ថែមគ្រឿងផ្សំ",
        invoices: "វិក្កយបត្រ",
        shop_managment: "ការគ្រប់គ្រងហាង",
        table: "តុ",
        product: "ផលិតផល",
        category: "ប្រភេទ",
        sale: "លក់",
        order: "ការកុម្ម៉ង់",
        user: "អ្នកប្រើប្រាស់",
        permission: "សិទ្ធិ",
        total_purchase: "ការទិញសរុប",
        total_paid: "ការបង់សរុប",
        outstanding_balance: "សមតុល្យនៅសល់",
        total_orders: "ការកុម្ម៉ង់សរុប",
        purchase_history: "ប្រវត្តិនៃការទិញ",
        new_purchase: "ការទិញថ្មី",
        ref_no: "លេខយោង",
        paid_amount: "ចំនួនបានបង់",
        balance: "សមតុល្យ",
        save: "រក្សាទុក",
        cancel: "បោះបង់",
        receive_date: "ថ្ងៃទទួល",
        note: "ចំណាំ",
        total_amount: "សរុបទឹកប្រាក់",
        receiving_now: "កំពុងទទួល",
        supplier_list: "បញ្ជីអ្នកផ្គត់ផ្គង់",
        name: "ឈ្មោះ",
        code: "កូដ",
        tel: "ទូរស័ព្ទ",
        email: "អ៊ីមែល",
        address: "អាសយដ្ឋាន",
        website: "គេហទំព័រ",
        created_at: "កាលបរិច្ឆេទបង្កើត",
        edit: "កែសម្រួល",
        delete: "លុប",
        add_new_supplier: "អ្នកផ្គត់ផ្គង់ថ្មី",
        edit_supplier: "កែសម្រួលអ្នកផ្គត់ផ្គង់",
        confirm_delete_supplier: "តើអ្នកប្រាកដថាចង់លុបទិន្នន័យនេះឬ?",
        supplier_deleted: "លុបទិន្នន័យដោយជោគជ័យ!",
        raw_material_list: "បញ្ជីគ្រឿងផ្សំ",
        material_name: "ឈ្មោះគ្រឿងផ្សំ",
        stock_status: "ស្ថានភាពស្តុក",
        last_cost: "ថ្លៃដើមចុងក្រោយ",
        active: "ដំណើរការ",
        inactive: "មិនដំណើរការ",
        add_new_material: "បន្ថែមគ្រឿងផ្សំថ្មី",
        edit_material: "កែសម្រួលគ្រឿងផ្សំ",
        initial_stock: "ស្តុកដំបូង",
        min_stock_alert: "ការជូនដំណឹងស្តុកទាប",
        in_stock: "មានក្នុងស្តុក",
        low_stock: "ស្តុកទាប",
        out_of_stock: "អស់ពីស្តុក",
        total_products_menu: "មុខម្ហូបទាំងអស់",
        low_stock_products: "មុខម្ហូបស្តុកទាប",
        low_stock_materials: "គ្រឿងផ្សំស្តុកទាប",
        stock_logs_adjustments: "កំណត់ត្រាស្តុក និងការកែម្រួល",
        manual_adjustment: "ការកែសម្រួលដោយដៃ",
        filter_by_item_type: "ចម្រោះតាមប្រភេទ",
        filter_by_type: "ចម្រោះតាមប្រតិបត្តិការ",
        date_time: "ថ្ងៃ និងម៉ោង",
        category: "ប្រភេទផលិតផល",
        transaction: "ប្រតិបត្តិការ",
        change: "ការផ្លាស់ប្តូរ",
        staff: "បុគ្គលិក",
        reason: "មូលហេតុ",
        stock_correction: "ការកែសម្រួលស្តុក",
        inventory_item_type: "ប្រភេទរបស់របរ",
        select_item: "ជ្រើសរើសរបស់របរ",
        action_type: "ប្រភេទសកម្មភាព",
        qty_change: "ចំនួនផ្លាស់ប្តូរ",
        remark_reason: "សម្គាល់ / មូលហេតុ",
        adjustment: "ការកែសម្រួល",
        waste: "ការបាត់បង់/ខូច",
        receive: "ការទទួល",
        unit: "ឯកតា",
        quantity_in_stock: "ចំនួនក្នុងស្តុក",
        branch_management: "ការគ្រប់គ្រងសាខា",
        manage_locations: "គ្រប់គ្រងទីតាំងអាជីវកម្ម និងទីស្នាក់ការរបស់អ្នក",
        add_new_branch: "បន្ថែមសាខាថ្មី",
        branch_name: "ឈ្មោះសាខា",
        location_address: "ទីតាំង / អាសយដ្ឋាន",
        contact_phone: "លេខទូរស័ព្ទទំនាក់ទំនង",
        set_as_main_hq: "កំណត់ជាទីស្នាក់ការកណ្តាល?",
        main_headquarter: "ទីស្នាក់ការកណ្តាល",
        setup_new_branch: "រៀបចំសាខាថ្មី",
        update_branch: "កែសម្រួលសាខា",
        delete_branch_confirm: "តើអ្នកប្រាកដថាចង់លុបសាខានេះមែនទេ? វានឹងអាចប៉ះពាល់ដល់ទិន្នន័យពាក់ព័ន្ធដូចជាការបញ្ជាទិញ និងស្តុក។",
        table_qr_setup: "ការរៀបចំ QR តុ",
        manage_table_qr: "បង្កើត និងគ្រប់គ្រងកូដ QR សម្រាប់តុនីមួយៗ",
        add_table: "បន្ថែមតុ",
        table_number_name: "លេខតុ / ឈ្មោះតុ",
        generate_table_qr: "បង្កើត QR តុ",
        order_detail: "លម្អិតការបញ្ជាទិញ",
        view_qr: "មើល QR",
        print_qr_tag: "បោះពុម្ព QR តុ",
        copy_link: "ចម្លងតំណភ្ជាប់",
        open_menu: "បើកមុខម្ហូប",
        qr_status: "ស្ថានភាព QR",
        ready: "រួចរាល់",
        missing: "បាត់",
        remove_table_confirm: "វានឹងលុបការរៀបចំ QR របស់តុនេះជាអចិន្ត្រៃយ៍។",
        confirm_delete: "បញ្ជាក់ការលុប",
        success: "ជោគជ័យ",
        failed: "បរាជ័យ",
        invalid_image_format: "អនុញ្ញាតតែឯកសាររូបភាពប៉ុណ្ណោះ",
        image_size_too_large: "ទំហំរូបភាពត្រូវតែតូចជាង ២មេកាបៃ",
        user_management: "ការគ្រប់គ្រងអ្នកប្រើប្រាស់",
        staff_identity: "អត្តសញ្ញាណបុគ្គលិក",
        business_role: "តួនាទីអាជីវកម្ម",
        contact_branch: "ទំនាក់ទំនង / សាខា",
        access_status: "ស្ថានភាពចូលប្រើ",
        management: "ការគ្រប់គ្រង",
        active_branches: "សាខាសកម្ម",
        total_personnel: "បុគ្គលិកសរុប",
        regular_team: "ក្រុមធម្មតា",
        expires: "ផុតកំណត់",
        staff_nodes: "ចំនួនបុគ្គលិក",
        lookup_placeholder: "ស្វែងរកតាមឈ្មោះ/លេខសម្គាល់...",
        new_staff_member: "សមាជិកបុគ្គលិកថ្មី",
        update_staff: "កែសម្រួលបុគ្គលិក",
        purge: "លុបចោល",
        view_only: "មើលតែប៉ុណ្ណោះ",
        permitted: "អនុញ្ញាត",
        suspended: "ផ្អាក",
        all_staff: "បុគ្គលិកទាំងអស់",
        executives: "នាយកប្រតិបត្តិ",
        admins: "អ្នកគ្រប់គ្រង",
        staff_limit_reached: "ចំនួនបុគ្គលិកដល់ដែនកំណត់សម្រាប់គម្រោងរបស់អ្នក",
        required: "តម្រូវឱ្យមាន",
        password_not_match: "លេខសម្ងាត់មិនត្រូវគ្នា",
        user_role: "តួនាទី",
        owner: "ម្ចាស់ហាង",
        executive: "នាយកប្រតិបត្តិ",
        security_permissions: "សុវត្ថិភាព និងសិទ្ធិអនុញ្ញាត",
        security_permissions_desc: "គ្រប់គ្រងអ្វីដែលតួនាទីអ្នកប្រើប្រាស់នីមួយៗអាចចូលប្រើប្រាស់បាននៅគ្រប់សាខា",
        select_user_role: "ជ្រើសរើសតួនាទីអ្នកប្រើប្រាស់",
        user_role_desc: "សិទ្ធិអនុញ្ញាតនឹងត្រូវបានអនុវត្តចំពោះអ្នកប្រើប្រាស់ទាំងអស់ដែលបានចាត់តាំងឱ្យតួនាទីនេះ។",
        pick_role_placeholder: "ជ្រើសរើសតួនាទីដើម្បីកំណត់រចនាសម្ព័ន្ធ",
        multi_branch_access: "ការចូលប្រើប្រាស់ច្រើនសាខា",
        multi_branch_access_desc: "សិទ្ធិអនុញ្ញាតដែលបានកំណត់នៅទីនេះគឺមានលក្ខណៈជាសកលនៅគ្រប់សាខាទាំងអស់។ បុគ្គលិកនឹងឃើញតែទិន្នន័យសម្រាប់សាខាដែលបានចាត់តាំងរបស់ពួកគេប៉ុណ្ណោះ។",
        module_permissions: "សិទ្ធិអនុញ្ញាតម៉ូឌុល",
        select_all: "ជ្រើសរើសទាំងអស់",
        permission_name: "ឈ្មោះសិទ្ធិ",
        navigation_path: "ផ្លូវរុករក",
        upload: "បង្ហោះ",
        yes: "បាទ/ចាស់",
        no: "ទេ",
        branch_management_desc: "មជ្ឈមណ្ឌលគ្រប់គ្រងសកលសម្រាប់ប្រតិបត្តិការច្រើនសាខា និងការត្រួតពិនិត្យប្រតិបត្តិ។",
        staff_management_desc: "គ្រប់គ្រងក្រុមអាជីវកម្ម តួនាទី និងការចូលប្រើប្រាស់រដ្ឋបាលរបស់អ្នក។",
        password: "លេខសម្ងាត់",
        report: "របាយការណ៍",
        pending_table: "តុរង់ចាំ",
        sound_on: "សំឡេងបើក",
        sound_off: "សំឡេងបិទ",
        need_restock: "ត្រូវការបំពេញស្តុក",
        purchase_receipt: "វិក្កយបត្រទិញ",
        dine_in: "ញ៉ាំក្នុងហាង",
        take_away: "ខ្ចប់ទៅផ្ទះ",
        customer_name: "ឈ្មោះអតិថិជន",
        table_label: "តុ",
        order_list: "បញ្ជីកុម្ម៉ង់",
        cart_empty: "កន្ត្រកទំនេរ",
        add_from_menu: "បន្ថែមមុខម្ហូបពីបញ្ជី",
        payment_details: "ព័ត៌មានទូទាត់",
        total_savings: "ការសន្សំសរុប",
        tax_fees: "ពន្ធ និងសេវាកម្ម",
        select_payment: "ជ្រើសរើសការទូទាត់",
        place_order: "បញ្ជាទិញ",
        customize_coffee: "កំណត់កាហ្វេរបស់អ្នក",
        mood: "ប្រភេទ",
        size: "ទំហំ",
        sugar_level: "កម្រិតស្ករ",
        order_completed: "ការកុម្ម៉ង់បានបញ្ចប់!",
        order_placed: "ការកុម្ម៉ង់បានជោគជ័យ!",
        new_order_received: "មានការកុម្ម៉ង់ថ្មីពីតុ!",
        hot: "ក្តៅ",
        ice: "ត្រជាក់",
        available: "អាចប្រើបាន",
        pending_orders: "រង់ចាំបញ្ជាទិញពីតុ",
        no_pending: "មិនមានការបញ្ជាទិញទេ",
        walk_in: "ចូលទិញផ្ទាល់",
        guest: "ភ្ញៀវ",
        refresh_list: "ទាញយកឡើងវិញ",
        unknown: "មិនស្គាល់",
        no_discount: "គ្មានការបញ្ចុះតម្លៃ",
        update: "កែសម្រួល",
        order_failed: "ការកុម្ម៉ង់បរាជ័យ!",
        fetch_branch_failed: "បរាជ័យក្នុងការទាញយកសាខា",
        fetch_table_failed: "បរាជ័យក្នុងការទាញយកតុ",
        operation_failed: "ប្រតិបត្តិការបរាជ័យ",
        scan_menu_order: "ស្កែនដើម្បីមើលបញ្ជីម្ហូប និងកុម្ម៉ង់",
        recipe: "រូបមន្ត",
        audit: "សវនកម្ម",
        off: "បិទ",
        update_item: "កែសម្រួលទំនិញ",
        save_item: "រក្សាទុកទំនិញ",
        choose_size: "ជ្រើសរើសទំហំ",
        label_required: "តម្រូវឱ្យមានស្លាក",
        price_required: "តម្រូវឱ្យមានតម្លៃ",
        category_required: "តម្រូវឱ្យមានប្រភេទ",
        enter_description: "បញ្ជាក់ការពិពណ៌នា",
        view: "មើល",
        performance_trends: "និន្នាការលទ្ធផល",
        top_selling_products: "ផលិតផលលក់ដាច់បំផុត",
        system_distribution: "ការបែងចែកប្រព័ន្ធ",
        total_revenue_growth: "កំណើនចំណូលសរុប",
        customer_retention: "ការរក្សាអតិថិជន",
        not_specified: "មិនបានបញ្ជាក់",
        no_phone: "គ្មានលេខទូរស័ព្ទ",
        create_branch: "បង្កើតសាខា",
        free_plan_limit: "អ្នកប្រើប្រាស់គម្រោងឥតគិតថ្លៃត្រូវបានកំណត់ត្រឹម ១ សាខាប៉ុណ្ណោះ។ សូមដំឡើងទៅ Pro សម្រាប់ការគាំទ្រច្រើនទីតាំង។",
        pro_plan_info: "អ្នកកំពុងប្រើប្រាស់គម្រោង Pro។ អ្នកអាចគ្រប់គ្រងសាខាច្រើនបានយ៉ាងរលូន។",
        goods_received_success: "ទំនិញត្រូវបានទទួល និងធ្វើបច្ចុប្បន្នភាពស្តុក!",
        create_purchase_failed: "បរាជ័យក្នុងការបង្កើតការទិញ",
        receive_goods_failed: "បរាជ័យក្នុងការទទួលទំនិញ",
        something_went_wrong: "មានបញ្ហាអ្វីមួយបានកើតឡើង",
        confirm_remove_raw_material: "តើអ្នកប្រាកដថាចង់លុបគ្រឿងផ្សំនេះមែនទេ?",
        no_image: "គ្មានរូបភាព",
        khqr_setting: "កំណត់កូដ QR ទូទាត់",
        upload_khqr: "បង្ហោះកូដ QR (KHQR)",
        khqr_image: "រូបភាពកូដ QR",
        daily_closing_title: "ការបិទបញ្ជីប្រចាំថ្ងៃ និងការបញ្ជាទិញ",
        daily_closing_desc: "ពិនិត្យមើលការលក់ប្រចាំថ្ងៃ និងផ្ទៀងផ្ទាត់បញ្ជី",
        total_orders_label: "សរុបបុង",
        dash_cash: "សាច់ប្រាក់",
        dash_aba: "ABA / QR",
        dash_wing: "Wing / ផ្សេងៗ",
        top_selling_label: "លក់ដាច់បំផុត",
        tab_today: "បិទបញ្ជីថ្ងៃនេះ",
        tab_history: "ប្រវត្តិនៃការបិទបញ្ជី",
        add_expense_btn: "បន្ថែមការចំណាយ",
        save_print_report: "រក្សាទុក និងបោះពុម្ព",
        open_shift_btn: "បើកថ្ងៃ",
        opening_cash_label: "លុយដើមគ្រា",
        opening_cash_sub: "សមតុល្យដើម",
        actual_cash_label: "លុយក្នុងថត",
        cash_in_drawer: "លុយក្នុងដៃជាក់ស្តែង",
        cash_sales_label: "លក់ជាសាច់ប្រាក់",
        cash_expenses_label: "ការចំណាយជាសាច់ប្រាក់",
        exchange_rate_label: "អត្រាប្តូរប្រាក់",
        remark_placeholder: "សម្គាល់ / 备注 (ឧទាហរណ៍៖ អតិថិជនជំពាក់ ឬបាត់លុយអាប់...)",
        difference_label: "ភាពខុសគ្នា",
        expected_label: "តុល្យភាពរំពឹងទុក",
        orders_this_shift: "ការបញ្ជាទិញក្នុងវេននេះ",
        refresh_btn: "ផ្ទុកឡើងវិញ",
        close_date: "ថ្ងៃបិទបញ្ជី",
        staff_role_label: "បុគ្គលិក / តួនាទី",
        actual_in_drawer: "លុយជាក់ស្តែង",
        total_sales_all: "លក់សរុបទាំងអស់",
        order_detail_title: "ព័ត៌មានលម្អិតបុង",
        order_summary: "សង្ខេបការបញ្ជាទិញ",
        items_ordered: "មុខទំនិញដែលបានកុម្ម៉ង់",
        quick_expense_title: "ចំណាយរហ័ស",
        expense_amount: "ចំនួនទឹកប្រាក់ចំណាយ",
        payment_type: "ប្រភេទនៃការទូទាត់",
        expense_cash_desc: "សាច់ប្រាក់ (ដកពីថត)",
        expense_bank_desc: "ធនាគារ / QR (មិនប៉ះសាច់ប្រាក់)",
        describe_expense: "ការពិពណ៌នាពីការចំណាយ (ឧទាហរណ៍៖ ទិញទឹកកក)",
        open_new_shift: "ការបើកវេនថ្មី",
        enter_opening_cash: "បញ្ចូលទឹកប្រាក់ដើមគ្រារបស់អ្នកដើម្បីចាប់ផ្តើម",
        authorized_by: "អនុញ្ញាតដោយ",
        open_shift_now: "បើកបញ្ជីឥឡូវនេះ",
        home_boutique: "ការបញ្ជាទិញ",
        discover: "ស្វែងរក",
        starred: "ចំណូលចិត្ត",
        profile_atelier: "គណនី",
        selected_collections: "បណ្តុំដែលបានជ្រើសរើស",
        house_favorites: "ភេសជ្ជៈពិសេសប្រចាំហាង",
        pure_perfection: "រសជាតិដ៏ល្អឥតខ្ចោះគ្រប់ពែង",
        taste_luxury: "រសជាតិដ៏ប្រណិតនៃ",
        fine_beans: "គ្រាប់កាហ្វេគុណភាព",
        signature_limited: "សាកល្បងរសជាតិអាថ៌កំបាំងដែលផលិតយ៉ាងសម្រិតសម្រាំងបំផុតសម្រាប់លោកអ្នក។",
        explore_now: "ស្វែងរកឥឡូវនេះ",
        search_product: "ស្វែងរកភេសជ្ជៈដែលអ្នកចូលចិត្ត...",
        search_results: "លទ្ធផលដែលរកឃើញ",
        related_products: "អ្នកប្រហែលជាចូលចិត្ត",
        established: "បង្កើតឡើងនៅឆ្នាំ",
        basket_empty: "មិនទាន់មានទំនិញក្នុងកន្ត្រកទេ",
        your_basket: "កន្ត្រករបស់អ្នក",
        place_order_now: "បញ្ជាទិញឥឡូវនេះ",
        subview_history: "ប្រវត្តិកុម្ម៉ង់",
        subview_settings: "ការកំណត់កម្មវិធី",
        accounting_class: "ចំណាត់ថ្នាក់គណនេយ្យ",
        cogs: "ថ្លៃដើមទំនិញ (COGS)",
        operational: "ការចំណាយប្រតិបត្តិការ (OpEx)",
        administrative: "រដ្ឋបាល",
        stock_audit_correction: "សវនកម្មស្តុក និងការកែម្រួល",
        transfer_status: "ស្ថានភាពផ្ទេរ",
        transfer_ref: "លេខយោងផ្ទេរ",
        from_branch: "ផ្ទេរចេញពី",
        to_branch: "ផ្ទេរចូលទៅ",
        stock_transfer_details: "លម្អិតការផ្ទេរស្តុក",
        stock_ledger_audit: "កំណត់ត្រាស្តុក និងសវនកម្ម",
        stock_to_stock_transfers: "ការផ្ទេរទំនិញរវាងសាខា",
        new_transfer_req: "សំណើផ្ទេរទំនិញថ្មី",
        transfer_note: "សម្គាល់ការផ្ទេរ",
        source_branch: "សាខាដើម",
        recipient_branch: "សាខាទទួល",
        accept_add_stock: "ទទួលយក និងបញ្ជាក់ចូលស្តុក",
        confirm_goods_receipt: "បញ្ជាក់ការទទួលទំនិញ",
        cancel_transfer_confirm: "ទំនិញនឹងត្រូវត្រឡប់ទៅសាខាដើមវិញ។",
        add_another_item: "បន្ថែមមុខទំនិញផ្សេងទៀត",
        cannot_transfer_same_branch: "មិនអាចផ្ទេរទំនិញទៅកាន់សាខាខ្លួនឯងបានទេ។ សូមជ្រើសរើសសាខាទទួលផ្សេងគ្នា។",
        validation_error: "បញ្ហាក្នុងការបញ្ជាក់",
        ok_btn: "យល់ព្រម",
        cancel_btn: "បោះបង់",
        authorized_by: "អនុញ្ញាតដោយ",
        discard: "បោះបង់",
        submit_audit: "បញ្ជូនសវនកម្ម",
        inventory_movement: "ចលនាស្តុក",
        qty_in_stock: "ចំនួនក្នុងស្តុក",
        no_ingredients_defined: "មិនទាន់មានគ្រឿងផ្សំនៅឡើយទេ",
        select_product_to_view_recipe: "ជ្រើសរើសផលិតផលដើម្បីមើល ឬគ្រប់គ្រងរូបមន្ត",
        please_select_ingredient: "សូមជ្រើសរើសគ្រឿងផ្សំ",
        search_ingredients: "ស្វែងរកគ្រឿងផ្សំ...",
        please_enter_qty: "សូមបញ្ចូលបរិមាណ",
        save_success: "បានរក្សាទុកដោយជោគជ័យ",
        cost_per_unit: "ថ្លៃដើម/ឯកតា",
        total_cost: "សរុប",
        recipe_total_cost: "តម្លៃដើមសរុបនៃរូបមន្ត",
        current_stock: "ក្នុងស្តុក",
        batch_no: "លេខបាច់ (Batch #)",
        expiry_date: "ថ្ងៃផុតកំណត់",
        tax: "ពន្ធ/VAT",
        payment_method: "មធ្យោបាយទូទាត់",
        cash: "សាច់ប្រាក់",
        bank: "ធនាគារ / ផ្ទេរ",
        discount_full: "ចំនួនបញ្ចុះតម្លៃ",
        grand_total: "សរុបរួម",
        unit: "ឯកតា",
        sign_in: "ចូលប្រើប្រាស់",
        language: "ភាសា",
        favorites: "សំណព្វ",
        starred: "បានផ្កាយ",
        home: "ទំព័រដើម",
        your_basket: "កន្រ្តករបស់អ្នក",
        basket_empty: "កន្រ្តកបច្ចុប្បន្ននៅទំនេរ",
        place_order_now: "បញ្ជាទិញឥឡូវនេះ",
        search_in_category: "ស្វែងរកក្នុង",
        category_label: "ប្រភេទ",
        no_results_found: "រកមិនឃើញលទ្ធផល",
        waiting_for_cashier: "រង់ចាំអ្នកគិតលុយ",
        brewing_cooking: "កំពុងឆុង / ធ្វើ",
        ready_pickup: "រួចរាល់សម្រាប់ទទួល",
        served_enjoy: "បានជូន និងរីករាយ",
        pending_status_desc: "ការកុម្ម៉ង់របស់អ្នកកំពុងត្រូវបានត្រួតពិនិត្យដោយអ្នកគិតលុយ។",
        cooking_status_desc: "បារីស្តារបស់យើងកំពុងរៀបចំភេសជ្ជៈដ៏ល្អឥតខ្ចោះសម្រាប់អ្នក។",
        ready_status_desc: "ភេសជ្ជៈរបស់អ្នករួចរាល់ហើយ! សូមអញ្ជើញមកទទួលនៅបញ្ជរ។",
        served_status_desc: "រីករាយជាមួយភេសជ្ជៈរបស់អ្នក! សង្ឃឹមថានឹងបានជួបអ្នកម្តងទៀត។",
        history: "ប្រវត្តិ",
        no_orders_found: "រកមិនឃើញការកុម្ម៉ង់ទេ",
        settings: "ការកំណត់",
        orders: "ការកុម្ម៉ង់",
        profile: "គណនី",
        add_to_basket: "បន្ថែមទៅកន្រ្តក",
        order_checkout: "ការទូទាត់ប្រាក់",
        service_fee: "សេវាសេវាកម្ម",
        free: "ឥតគិតថ្លៃ",
        placing_order: "កំពុងបញ្ជូនការកុម្ម៉ង់...",
        unit_price: "តម្លៃរាយ",
        back_to_home: "ត្រឡប់ទៅទំព័រដើម",
        order_received: "ទទួលបានការកុម្ម៉ង់",
        guest: "ភ្ញៀវ",
        order_success_msg: "ការកុម្ម៉ង់បានជោគជ័យ! បារីស្តាកំពុងរៀបចំភេសជ្ជៈជូនអ្នក។ ☕",
        order_failed_msg: "មិនអាចបញ្ជូនការកុម្ម៉ង់បានទេ។",
        order_status_update_failed: "ការកុម្ម៉ង់ត្រូវបានបញ្ជូន ប៉ុន្តែមិនអាចបង្ហាញស្ថានភាពបាន។",
        premium_experience: "បទពិសោធន៍ដ៏អស្ចារ្យ",
        hi: "សួស្តី",
        special_offer: "ការផ្តល់ជូនពិសេស",
        fresh_brewed: "ឆុងថ្មីៗក្តៅៗ",
        happiness: "ក្តីសុខ",
        hurry_up: "ប្រញាប់ឡើង! ការផ្តល់ជូនជិតផុតកំណត់ហើយ",
        browse_mode: "របៀបមើលមុខម្ហូប",
        browse_mode_msg: "លោកអ្នកកំពុងស្ថិតក្នុងរបៀបមើលមុខម្ហូប។ សូមស្កែនកូដ QR នៅលើតុដើម្បីធ្វើការកុម្ម៉ង់។",
        scan_to_order: "ស្កែន QR ដើម្បីកុម្ម៉ង់",
        please_scan_msg: "សូមស្កែនកូដ QR នៅលើតុរបស់អ្នក ដើម្បីចាប់ផ្តើមជ្រើសរើសភេសជ្ជៈដែលអ្នកចូលចិត្ត។",
        select_branch_to_browse: "ឬជ្រើសរើសសាខាដើម្បីមើលមុខទំនិញ",
        staff_portal: "ច្រកចូលបុគ្គលិក",
        ready_to_serve: "ត្រៀមខ្លួនបម្រើលោកអ្នក",
        no_branch_selected: "មិនទាន់បានជ្រើសរើសសាខា",
        stock_valuation: "តម្លៃស្តុកសរុប",
        expiring_soon: "ជិតផុតកំណត់",
        stock_insights: "ការវិភាគស្តុក",
        total_items: "មុខទំនិញសរុប",
        reorder_needed: "ត្រូវការកម្ម៉ង់បន្ថែម",
        view_inventory: "មើលបញ្ជីស្តុក",
        financial_trend: "និន្នាការហិរញ្ញវត្ថុ",
        live_summary_today: "សង្ខេបបច្ចុប្បន្ន (ថ្ងៃនេះ)",
        todays_income: "ចំណូលថ្ងៃនេះ",
        todays_expense: "ចំណាយថ្ងៃនេះ",
        net_daily_profit: "ចំណេញសុទ្ធប្រចាំថ្ងៃ",
        period_revenue: "ចំណូលតាមកាលបរិច្ឆេទ",
        period_expenses: "ចំណាយតាមកាលបរិច្ឆេទ",
        avg_cost: "តម្លៃមធ្យម",
        par_level: "កម្រិតស្តុកសមស្រប",
        min_alert: "កម្រិតទាបបំផុត",
        product_category_header: "មុខទំនិញ និងប្រភេទ",
        unit_price_header: "តម្លៃរាយ",
        stock_header: "ស្តុក",
        table_dashboard: "គ្រប់គ្រងតុ",
        free_status: "ទំនេរ",
        occupied_status: "មានភ្ញៀវ",
        available_status: "អាចប្រើបាន",
        people_count: "ចំនួនភ្ញៀវ",
        shift_started: "វេនចាប់ផ្តើមនៅ",
        close_shift: "បិទវេន",
        discover_placeholder: "ស្វែងរកភេសជ្ជៈ ឬអាហារ...",
        held_drafts: "បញ្ជីរង់ចាំ",
        grid_view: "ក្រឡា",
        list_view: "បញ្ជី",
        sync_btn: "ធ្វើបច្ចុប្បន្នភាព",
        full_screen: "ពេញអេក្រង់",
        purchase_receipt_header: "វិក្កយបត្រលក់",
        sent_status: "ផ្ញើរួច",
        save_btn: "រក្សាទុក",
        order_items_label: "បញ្ជីមុខទំនិញ",
        subtotal_label: "សរុបរង",
        discount_label: "បញ្ចុះតម្លៃ",
        total_label: "សរុប",
        khr_label: "រៀល",
        general_settings_desc: "គ្រប់គ្រងព័ត៌មានអាជីវកម្ម និងការកំណត់ប្រព័ន្ធលក់របស់លោកអ្នក",
        business_info_header: "ព័ត៌មានអាជីវកម្ម",
        business_name_label: "ឈ្មោះអាជីវកម្ម",
        owner_name_label: "ឈ្មោះម្ចាស់",
        phone_number_label: "លេខទូរស័ព្ទ",
        email_address_label: "អាសយដ្ឋានអ៊ីមែល",
        address_label: "អាសយដ្ឋាន",
        website_url_label: "គេហទំព័រ / URL",
        pos_financial_config_header: "ការកំណត់ហិរញ្ញវត្ថុ & POS",
        currency_symbol_label: "និមិត្តសញ្ញារូបិយប័ណ្ណ",
        exchange_rate_label: "អត្រាប្តូរប្រាក់ (១ ដុល្លារ = ? រៀល)",
        vat_tax_label: "ពន្ធអាករ / VAT (%)",
        service_charge_label: "សេវាសេវាកម្ម (%)",
        save_all_changes_btn: "រក្សាទុកការផ្លាស់ប្តូរទាំងអស់",
        open_shift_now_btn: "បើកវេនលក់ឥឡូវនេះ",
        mobile_app_promo_tab: "កម្មវិធីទូរស័ព្ទ & ប្រូម៉ូសិន",
        promo_banner_header: "បដាប្រូម៉ូសិន (Home Banner)",
        promo_active_status: "ស្ថានភាពដំណើរការ",
        promo_tag_label: "ស្លាកប្រូម៉ូសិន (ឧ. បើកសម្ពោធ)",
        promo_title_label: "ចំណងជើងបដា",
        promo_desc_label: "ការពិពណ៌នាបដា",
        promo_image_label: "តំណភ្ជាប់រូបភាពផ្ទៃក្រោយ",
        global_discount_header: "ការបញ្ចុះតម្លៃជាភាគរយសកល",
        discount_scope_label: "វិសាលភាពនៃការបញ្ចុះតម្លៃ",
        buy_x_get_y_header: "ប្រព័ន្ធប្រូម៉ូសិន៖ ទិញ X ថែម Y",
        promo_scope_label: "វិសាលភាពនៃប្រូម៉ូសិន",
        start_date_label: "ថ្ងៃចាប់ផ្តើម",
        end_date_label: "ថ្ងៃបញ្ចប់",
        category_tab: "ការគ្រប់គ្រងប្រភេទមុខទំនិញ",
        printing_workflow_header: "ការកំណត់លំហូរការងារបោះពុម្ព",
        auto_print_label: "បោះពុម្ពដោយស្វ័យប្រវត្តិពេលទូទាត់",
        auto_print_desc: "បើកផ្ទាំងបោះពុម្ពដោយស្វ័យប្រវត្តិបន្ទាប់ពីលក់រួចរាល់",
        execution_order_header: "លំដាប់នៃការបោះពុម្ព",
        print_priority_label: "តើមួយណាគួរបោះពុម្ពមុនគេ?",
        label_first_option: "ស្លាកសញ្ញា (Sticker) មុនគេ",
        invoice_first_option: "វិក្កយបត្រ (Receipt) មុនគេ",
        doc_availability_header: "ការបើកដំណើរការឯកសារ",
        enable_invoice_label: "បើកដំណើរការវិក្កយបត្រអតិថិជន",
        enable_label_stickers: "បើកដំណើរការស្លាកបិទកែវ (Stickers)",
        enable_kitchen_ticket: "បើកដំណើរការសន្លឹកបញ្ជាផ្ទះបាយ",
        pro_tip_label: "គន្លឹះពិសេស",
        kds_header: "KDS - ប្រព័ន្ធបង្ហាញបញ្ជាទិញក្នុងផ្ទះបាយ",
        history_btn: "ប្រវត្តិ",
        refresh_btn: "ធ្វើបច្ចុប្បន្នភាព",
        auto_refresh_on: "ធ្វើបច្ចុប្បន្នភាពស្វ័យប្រវត្តិ៖ បើក",
        auto_refresh_off: "ធ្វើបច្ចុប្បន្នភាពស្វ័យប្រវត្តិ៖ បិទ",
        takeaway_label: "ខ្ចប់ទៅផ្ទះ",
        dine_in_label: "ញ៉ាំនៅទីនេះ",
        pending_status: "កំពុងរង់ចាំ",
        preparing_status: "កំពុងរៀបចំ",
        done_status: "រួចរាល់",
        start_preparing_btn: "ចាប់ផ្តើមរៀបចំ",
        finish_preparing_btn: "បញ្ចូន",
        kds_history_title: "ប្រវត្តិ KDS (ថ្ងៃនេះ)",
        show_active_btn: "បង្ហាញបញ្ជីកំពុងដំណើរការ",
        mark_ready_btn: "រួចរាល់",
        mark_served_btn: "បានបម្រើជូន",
        served_today_empty: "មិនទាន់មានការបម្រើជូននៅថ្ងៃនេះទេ",
        active_tickets_empty: "មិនទាន់មានបញ្ជីរង់ចាំការរៀបចំនៅឡើយ",
        balanced_status: "ត្រឹមត្រូវ",
        discrepancy_status: "ខុសគ្នា",
        status_label: "ស្ថានភាព",
        print_receipt_btn: "បោះពុម្ពបង្កាន់ដៃ",
        scan_barcode_placeholder: "ស្កេនបារកូដ ឬវាយបញ្ចូល...",
        camera_btn: "កាមេរ៉ា",
        close_camera_btn: "បិទ",
        receive_now_label: "ទទួលឥឡូវនេះ",
        confirm_receiving_btn: "បញ្ជាក់ការទទួល",
        batch_label: "លេខឡូត៍/បាច់",
        expiry_label: "ថ្ងៃផុតកំណត់",
        order_qty_label: "ចំនួនកម្ម៉ង់",
        rec_qty_label: "ទទួលរួច",
        product_label: "មុខទំនិញ",
        unit_label: "ឯកតា",
        select_date_placeholder: "ជ្រើសរើសថ្ងៃ",
        show_all_btn: "បង្ហាញទាំងអស់",
        save_receiving_btn: "រក្សាទុកការទទួល",
        invoice_placeholder: "លេខវិក្កយបត្រ",
        cash_method: "សាច់ប្រាក់",
        bank_method: "ធនាគារ",
        request_status: "ស្នើសុំ",
        pending_status_simple: "កំពុងរង់ចាំ",
        received_status: "បានទទួល",
        product_list_header: "បញ្ជីមុខទំនិញ",
        quantity_label: "បរិមាណ",
        cost_price_label: "តម្លៃដើម",
        unit_pcs: "កញ្ចប់/ដប/ដើម (Pcs)",
        unit_box: "ប្រអប់ (Box)",
        unit_case: "កេស/ឡូ (Case)",
        available_products: "ចំនួនមុខទំនិញលក់",
        raw_materials_ledger: "ចំនួនវត្ថុធាតុដើម",
        product_alerts: "ការជូនដំណឹងទំនិញ",
        ingredient_alerts: "ការជូនដំណឹងគ្រឿងផ្សំ",
        items_low: "មុខទំនិញជិតអស់ពីស្តុក",
        stock_ledger_audit_desc: "តម្លាភាពសម្រាប់រាល់ចលនាស្តុក និងការកែប្រែក្នុងប្រព័ន្ធ",
        date_and_time_label: "ថ្ងៃ និង ម៉ោង",
        item_category_label: "ប្រភេទ",
        item_name_label: "ឈ្មោះទំនិញ",
        transaction_label: "ប្រតិបត្តិការ",
        change_label: "បំរែបំរួល",
        balance_label: "ស្តុកនៅសល់",
        authorized_by_label: "អនុម័តដោយ",
        reason_remark_label: "មូលហេតុ / ចំណាំ",
        sale_label: "លក់ចេញ",
        movements_found: "កំណត់ត្រាដែលបានរកឃើញ",
        close_shift_title: "បិទវេនលក់ / បិទបញ្ជី",
        sales_summary_label: "សេចក្តីសង្ខេបនៃការលក់",
        cash_sales_label: "លក់សាច់ប្រាក់ ($)",
        aba_payments_label: "ទូទាត់តាម ABA ($)",
        wing_payments_label: "ទូទាត់តាម Wing ($)",
        total_sales_label: "សរុបការលក់",
        total_expenses_label: "សរុបការចំណាយ",
        cash_counting_label: "ការរាប់សាច់ប្រាក់",
        expected_in_drawer_label: "សាច់ប្រាក់រំពឹងទុកក្នុងថត",
        actual_cash_usd_label: "លុយដុល្លាររាប់ជាក់ស្តែង (USD)",
        actual_cash_khr_label: "លុយរៀលរាប់ជាក់ស្តែង (KHR)",
        total_variance_label: "សរុបភាពខុសគ្នា (USD)",
        remark_placeholder: "កំណត់សម្គាល់ផ្សេងៗអំពីវេនលក់នេះ...",
        confirm_close_shift_btn: "បញ្ជាក់ការបិទវេន",
        basic_details_title: "ព័ត៌មានមូលដ្ឋាន",
        inventory_media_title: "ស្តុក និង រូបភាព",
        cooking_options_title: "ការរៀបចំ និង ជម្រើសបន្ថែម",
        taste_instructions_label: "រសជាតិ / ការណែនាំពិសេស",
        portions_sizes_label: "ចំណែក / ទំហំ",
        side_dishes_extras_label: "គ្រឿងបន្ថែម / ជម្រើសក្រៅបញ្ជី",
        medical_specs_title: "ព័ត៌មានលម្អិតផ្នែកវេជ្ជសាស្ត្រ",
        generic_name_label: "ឈ្មោះទូទៅ (សារធាតុគីមី)",
        strength_label: "កម្រិតថ្នាំ (mg/ml)",
        medical_note: "ចំណាំ៖ ព័ត៌មានទាំងនេះនឹងបង្ហាញនៅលើស្លាកថ្នាំ និងសម្រាប់តាមដានថ្ងៃផុតកំណត់។",
        packaging_units_label: "ការវេចខ្ចប់ / ឯកតា",
        dosage_instructions_label: "របៀបប្រើប្រាស់ / កម្រិតប្រើប្រាស់",
        price_per_size_msg: "តម្លៃតាមទំហំនឹងជំនួសតម្លៃដើម",
        medical_info_label: "ព័ត៌មានវេជ្ជសាស្ត្រ",
        expiry_column_label: "ថ្ងៃផុតកំណត់",
        recipe_config_title: "ការកំណត់រូបមន្តផលិតផល",
        est_cost_per_cup: "ថ្លៃដើមប៉ាន់ស្មានក្នុង ១កែវ",
        selling_price_label: "តម្លៃលក់ចេញ",
        gross_profit_label: "ប្រាក់ចំណេញដុល",
        select_ingredient_label: "ជ្រើសរើសគ្រឿងផ្សំ",
        usage_qty_label: "បរិមាណប្រើប្រាស់",
        add_ingredient_link: "បន្ថែមគ្រឿងផ្សំថ្មី",
        sync_recipe_btn: "រក្សាទុករូបមន្ត",
        profit_margin: "ភាគរយចំណេញ",
        value_stock_label: "តម្លៃ និង ស្តុក",
        in_stock_label: "ក្នុងស្តុក",
        ready_to_serve_label: "មានស្រាប់",
        made_to_order_label: "ឆុងតាមរូបមន្ត",
        recipe_tooltip: "រូបមន្ត និង គ្រឿងផ្សំ",
        physical_stock_audit: "ត្រួតពិនិត្យស្តុកជាក់ស្តែង",
        start_new_audit: "ចាប់ផ្តើមការរាប់ស្តុកថ្មី",
        extra_stock_label: "ទំនិញលើស",
        missing_stock_label: "ទំនិញបាត់",
        audit_commit_confirm: "តើលោកអ្នកពិតជាចង់ធ្វើបច្ចុប្បន្នភាពចំនួនស្តុកមែនទេ?",
        audit_commit_confirm_desc: "វានឹងបង្កើតការកែសម្រួលចំនួន {n} មុខដោយស្វ័យប្រវត្តិ ដើម្បីឱ្យត្រូវនឹងការរាប់ជាក់ស្តែងរបស់លោកអ្នក។",
        audit_instructions: "សូមជ្រើសរើសប្រភេទដើម្បីចាប់ផ្តើមរាប់ស្តុក។ ប្រព័ន្ធនឹងជួយលោកអ្នកស្វែងរកទំនិញដែលបាត់ ឬលើស រួចធ្វើបច្ចុប្បន្នភាពស្តុកដោយស្វ័យប្រវត្តិ។",
        audit_product_title: "ការត្រួតពិនិត្យស្តុកផលិតផល",
        audit_material_title: "ការត្រួតពិនិត្យស្តុកគ្រឿងផ្សំ",
        audit_items_count: "កំពុងត្រួតពិនិត្យ {n} មុខទំនិញ",
        system_qty_label: "ចំនួនក្នុងបញ្ជី",
        physical_count_label: "ចំនួនរាប់ជាក់ស្តែង",
        variance_label: "ចំនួនខុសគ្នា",
        audit_success_msg: "ការត្រួតពិនិត្យបានជោគជ័យ! បានធ្វើបច្ចុប្បន្នភាពទំនិញបាត់/លើសចំនួន {successCount}/{total} មុខ។",
        no_variance_msg: "មិនមានទំនិញបាត់ ឬលើសឡើយ។ ស្តុករបស់លោកអ្នកត្រឹមត្រូវ ១០០%!",
        complete_commit_btn: "បញ្ចប់ និង រក្សាទុកការរាប់ស្តុក",
        stock_intelligence_title: "ការព្យាករណ៍ស្តុក",
        days_left_label: "ប៉ាន់ស្មានថ្ងៃដែលនៅសល់",
        run_out_date_label: "ថ្ងៃដែលនឹងអស់ពីស្តុក",
        replenish_urgent: "ត្រូវបញ្ជាទិញទំនិញបន្ថែមជាបន្ទាន់",
        stock_health_good: "កម្រិតស្តុកមានសុវត្ថិភាព",
        avg_daily_usage: "ការប្រើប្រាស់មធ្យមភាគ/ថ្ងៃ",
        adjust_now_btn: "កែសម្រួលភ្លាមៗ",
        go_to_purchase: "ទៅកាន់ការទិញចូល",
        stock_adj_desc: "កែសម្រួលស្តុកដោយដៃ ក្នុងករណីមានការខូចខាត បាត់បង់ ឬការរាប់ស្តុកជាក់ស្តែង។",
        finished_product_opt: "ផលិតផលសម្រេច",
        raw_material_opt: "វត្ថុធាតុដើម",
        qty_adj_placeholder: "ឧ. ១០ ដើម្បីថែម, -៥ ដើម្បីដកចេញ",
        reason_placeholder: "ជ្រើសរើសមូលហេតុ...",
        remark_optional: "កំណត់សម្គាល់បន្ថែម (ជម្រើស)",
        profit_analysis_title: "វិភាគប្រាក់ចំណេញ",
        menu_engineering_label: "ចំណាត់ថ្នាក់មុខម្ហូប",
        star_item_label: "Star (លក់ដាច់ខ្លាំង & ចំណេញខ្ពស់)",
        plowhorse_item_label: "Plowhorse (លក់ដាច់ តែចំណេញទាប)",
        puzzle_item_label: "Puzzle (ចំណេញខ្ពស់ តែលក់មិនសូវដាច់)",
        dog_item_label: "Dog (លក់មិនដាច់ & ចំណេញទាប)",
        margin_per_unit: "ចំណេញក្នុងមួយកែវ",
        total_contribution: "ចំណែកចំណេញសរុប",
        popularity_rank: "ចំណាត់ថ្នាក់ប្រជាប្រិយភាព",
        rec_star: "ទំនិញចំណេញខ្ពស់! គួរជំរុញការផ្សព្វផ្សាយបន្ថែម។",
        rec_plowhorse: "លក់ដាច់តែចំណេញតិច។ គួរកាត់បន្ថយថ្លៃដើមគ្រឿងផ្សំ។",
        rec_puzzle: "ចំណេញខ្ពស់តែលក់មិនសូវដាច់។ គួរបង្កើតប្រូម៉ូសិនទិញថែម។",
        rec_dog: "លទ្ធផលមិនល្អ។ គួរពិចារណាដកចេញ ឬកែច្នៃថ្មី។",
        reason_barista_error: "កំហុសបារីស្តា (ធ្វើខុស/រសជាតិខុស)",
        reason_spillage: "ខ្ប់/ហៀរ/ជ្រុះ (ទំនិញខូចខាត)",
        reason_expired: "ទំនិញផុតកំណត់",
        reason_sampling: "ការសាកល្បងរសជាតិ (Sampling)",
        reason_store_use: "ប្រើប្រាស់ក្នុងហាង",
        reason_correction: "ការកែសម្រួលស្តុកទូទៅ",
        shift_audit_title: "ការបិទវេន និងសវនកម្មសាច់ប្រាក់",
        expected_cash_label: "សាច់ប្រាក់រំពឹងទុក (តាមប្រព័ន្ធ)",
        actual_cash_label: "សាច់ប្រាក់រាប់ជាក់ស្តែង",
        cash_variance_label: "ភាពខុសគ្នាសាច់ប្រាក់ (+/-)",
        shift_report_summary: "សេចក្តីសង្ខេបរបាយការណ៍វេន",
        opening_cash_label: "សាច់ប្រាក់ដើមគ្រា",
        total_sales_cash: "លក់សរុប (សាច់ប្រាក់)",
        total_sales_online: "លក់សរុប (អនឡាញ/កាត)",
        closing_note_placeholder: "កំណត់សម្គាល់បន្ថែមសម្រាប់ការបិទវេននេះ",
        business_insights_title: "សុខភាពអាជីវកម្ម",
        wastage_intelligence_title: "វិភាគការបាត់បង់",
        total_loss_value: "តម្លៃបាត់បង់សរុប",
        waste_reason_mix: "មូលហេតុនៃការបាត់បង់",
        top_wasted_items: "ទំនិញដែលខូចខាតច្រើនបំផុត",
        loss_by_category: "ការបាត់បង់តាមប្រភេទ",
        barista_error_label: "ឆុងខុស/រសជាតិមិនត្រូវ",
        spillage_label: "កំពប់/បែកបាក់",
        expired_label: "ហួសកាលបរិច្ឆេទ",
        internal_use_label: "ប្រើប្រាស់ក្នុងហាង",
        cost_impact_label: "ផលប៉ះពាល់លើដើមទុន",
        net_profit_intelligence_title: "ចំណេញសុទ្ធ & P&L",
        gross_profit_label: "ចំណេញដុល (Gross Profit)",
        total_expenses_label: "ការចំណាយសរុប",
        net_profit_label: "ចំណេញសុទ្ធ (Net Profit)",
        cogs_label: "ថ្លៃដើមទំនិញ (COGS)",
        operating_margin: "ភាគរយចំណេញ",
        p_and_l_summary: "សេចក្តីសង្ខេបហិរញ្ញវត្ថុ",
        financial_health_msg: "ស្ថានភាពហិរញ្ញវត្ថុ",
        profit_breakdown: "បំណែងចែកហិរញ្ញវត្ថុ",
        purchase_unit_label: "ឯកតាទិញពីអ្នកផ្គត់ផ្គង់",
        conversion_rate_label: "មេគុណបំលែង (ស្មើនឹងប៉ុន្មានឯកតាស្តុក?)",
        conversion_hint: "ឧទាហរណ៍៖ ១ កេស = ១២ កំប៉ុង (វាយលេខ ១២)",
        base_unit_label: "ឯកតាប្រើប្រាស់ក្នុងស្តុក",
        reorder_intelligence_title: "ណែនាំការទិញទំនិញ",
        days_until_out_of_stock: "ថ្ងៃដែលនឹងអស់ស្តុក",
        recommended_order_qty: "ចំនួនណែនាំឱ្យទិញថែម",
        create_po_now: "បង្កើតវិក្កយបត្រទិញភ្លាម",
        out_of_stock_risk: "ហានិភ័យដាច់ស្តុក",
        safe_stock_level: "កម្រិតស្តុកសុវត្ថិភាព",
        reorder_hint: "ប្រព័ន្ធណែនាំឱ្យលោកអ្នកទិញទំនិញទាំងនេះ ដើម្បីកុំឱ្យដាច់ស្តុកក្នុងសប្តាហ៍ក្រោយបាទ។",
        net_sales_label: "លក់សុទ្ធថ្ងៃនេះ",
        order_count_label: "ចំនួនវិក្កយបត្រសរុប",
        avg_order_value: "ចំណាយមធ្យម/វិក្កយបត្រ",
        peak_hours_analysis: "ការវិភាគម៉ោងមមាញឹក",
        category_mix_label: "ចំណែកលក់តាមប្រភេទ",
        busiest_time_label: "ម៉ោងដែលមមាញឹកបំផុត",
        sales_trend_label: "និន្នាការលក់តាមម៉ោង",
        morning_briefing: "របាយការណ៍សង្ខេបពេលព្រឹក",
        morning_briefing_desc: "នេះគឺជាសេចក្តីសង្ខេបអាជីវកម្មរបស់លោកអ្នកពីម្សិលមិញ",
        yesterday_revenue: "ចំណូលពីម្សិលមិញ",
        yesterday_profit: "ចំណេញសុទ្ធពីម្សិលមិញ",
        top_performer: "បុគ្គលិកឆ្នើម",
        best_selling_item: "មុខម្ហូបលក់ដាច់បំផុត",
        new_vips: "សមាជិក VIP ថ្មី",
        digital_receipt_title: "វិក្កយបត្រឌីជីថល",
        scan_to_view: "ស្កេនដើម្បីមើលក្នុងទូរស័ព្ទ",
        done_btn: "រួចរាល់",
        loyalty_portal: "ផតថលសមាជិក VIP",
        menu_board_label: "ផ្ទាំងបញ្ជីមុខម្ហូបឌីជីថល",
        waste_label: "កត់ត្រាការខូចខាត/ខ្ជះខ្ជាយ",
        forecast_label: "ការព្យាករណ៍តម្រូវការ AI",
        marketing_label: "យុទ្ធនាការទីផ្សារ និង CRM",
        kds_label: "ប្រព័ន្ធបង្ហាញការកម្ម៉ង់ក្នុងផ្ទះបាយ",
        performance_label: "សមិទ្ធផលបុគ្គលិក & ប្រាក់លើកទឹកចិត្ត",
    },
};
