export const CAMBODIA_GEO = {
    "Phnom Penh": ["Chamkar Mon", "Daun Penh", "Prampir Meakkakra", "Tuol Kork", "Dangkor", "Meanchey", "Russey Keo", "Sen Sok", "Pou Senchey", "Chroy Changvar", "Prek Pnov", "Chbar Ampov", "Boeng Keng Kang", "Kamboul"],
    "Banteay Meanchey": ["Mongkol Borei", "Phnum Srok", "Preah Netr Preah", "Ou Chrov", "Serei Saophoan", "Thma Puok", "Svay Chek", "Malai", "Paoy Paet"],
    "Battambang": ["Banreak", "Battambang", "Bavel", "Ek Phnum", "Kous Kralor", "Moung Ruessei", "Phnum Proek", "Ratanak Mondol", "Sangke", "Samlout", "Sampov Loun", "Thma Koul", "Koas Krala"],
    "Kampong Cham": ["Batheay", "Chamkar Leu", "Cheung Prey", "Kampong Cham", "Kampong Siem", "Kang Meas", "Koh Sotin", "Prey Chhor", "Srey Santhor", "Stung Trang"],
    "Kampong Chhnang": ["Baribour", "Chol Kiri", "Kampong Chhnang", "Kampong Leaeng", "Kampong Tralach", "Prey Nob", "Rolea B'ier", "Sameakki Mean Chey", "Tuek Phos"],
    "Kampong Speu": ["Basedth", "Chbar Mon", "Kong Pisei", "Ou Bak Roteh", "Phnum Sruoch", "Samraong Tong", "Thpong", "Odongk Meanchey", "Aoral"],
    "Kampong Thom": ["Baray", "Kampong Svay", "Stung Saen", "Prasat Balangk", "Prasat Sambour", "Sandaan", "Santuk", "Stoung", "Taing Kouk"],
    "Kampot": ["Angkor Chey", "Banteay Meas", "Chhouk", "Chum Kiri", "Dang Tong", "Kampong Trach", "Kampot", "Tuek Chhou"],
    "Kandal": ["Angk Snuol", "Kandal Stueng", "Koh Thum", "Leuk Dek", "Lvea Aem", "Mukh Kampool", "Ou Reang Ov", "Ponhea Leu", "S'ang", "Ta Khmau", "Sampov Poun"],
    "Kep": ["Kep", "Damnak Chang'aeur"],
    "Koh Kong": ["Botum Sakor", "Kiri Sakor", "Koh Kong", "Smach Mean Chey", "Mondol Seima", "Srae Ambel", "Thma Bang"],
    "Kratie": ["Chhlong", "Kratie", "Prek Prasap", "Sambour", "Snuol", "Ou Krieng Senchey"],
    "Mondulkiri": ["Kaev Seima", "Koh Nhek", "Ou Reang", "Pech Chreada", "Sen Monorom"],
    "Oddar Meanchey": ["Anlong Veng", "Banteay Ampil", "Chong Kal", "Samraong", "Trapeang Prasat"],
    "Pailin": ["Pailin", "Sala Krau"],
    "Preah Sihanouk": ["Preah Sihanouk", "Prey Nob", "Stueng Hav", "Kampong Seila", "Koh Rong"],
    "Preah Vihear": ["Chey Saen", "Chhaeb", "Choam Ksant", "Kulean", "Rovieng", "Sangkom Thmei", "Tbaeng Mean Chey", "Preah Vihear"],
    "Prey Veng": ["Ba Phnum", "Kamchay Mear", "Kampong Trabaek", "Kanhchriech", "Me Sang", "Peam Chor", "Peam Ro", "Pea Reang", "Preah Sdach", "Prey Veng", "Sithor Kandal", "Svay Antor"],
    "Pursat": ["Bakan", "Kandieng", "Krakor", "Phnum Kravanh", "Pursat", "Veal Veaeng", "Talou Senchey"],
    "Ratanakiri": ["Andoung Meas", "Ban Lung", "Bar Kaev", "Koun Mom", "Lumphat", "Ou Chum", "Ou Ya Dav", "Ta Veaeng", "Veun Sai"],
    "Siem Reap": ["Angkor Chum", "Angkor Thum", "Banteay Srei", "Chi Kraeng", "Kralanh", "Puok", "Prasat Bakong", "Siem Reap", "Soutr Nikum", "Srei Snam", "Svay Leu", "Varin"],
    "Stung Treng": ["Sesan", "Siem Bouk", "Siem Pang", "Stung Treng", "Thala Barivat", "Borei Ou Svay Sen Chey"],
    "Svay Rieng": ["Chantrea", "Kampong Rou", "Romduol", "Romeas Haek", "Svay Chrum", "Svay Rieng", "Svay Teab", "Bavet"],
    "Takeo": ["Angkor Borei", "Bati", "Bourei Cholsar", "Kiri Vong", "Koh Andaet", "Prey Kabbas", "Samraong", "Takeo", "Tram Kak", "Treang"],
    "Tboung Khmum": ["Dambae", "Krouch Chhmar", "Memot", "Ou Reang Ov", "Ponhea Kraek", "Suong", "Tboung Khmum"]
};
